// +build !ignore_autogenerated

/*
Copyright 2020 The OpenEBS Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	v1alpha1 "github.com/openebs/api/pkg/apis/openebs.io/v1alpha1"
	openebsio "github.com/openebs/api/pkg/internalapis/apis/openebs.io"
	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*v1alpha1.BlockDevice)(nil), (*openebsio.BlockDevice)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BlockDevice_To_openebsio_BlockDevice(a.(*v1alpha1.BlockDevice), b.(*openebsio.BlockDevice), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openebsio.BlockDevice)(nil), (*v1alpha1.BlockDevice)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openebsio_BlockDevice_To_v1alpha1_BlockDevice(a.(*openebsio.BlockDevice), b.(*v1alpha1.BlockDevice), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.BlockDeviceClaim)(nil), (*openebsio.BlockDeviceClaim)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BlockDeviceClaim_To_openebsio_BlockDeviceClaim(a.(*v1alpha1.BlockDeviceClaim), b.(*openebsio.BlockDeviceClaim), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openebsio.BlockDeviceClaim)(nil), (*v1alpha1.BlockDeviceClaim)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openebsio_BlockDeviceClaim_To_v1alpha1_BlockDeviceClaim(a.(*openebsio.BlockDeviceClaim), b.(*v1alpha1.BlockDeviceClaim), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.BlockDeviceClaimList)(nil), (*openebsio.BlockDeviceClaimList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BlockDeviceClaimList_To_openebsio_BlockDeviceClaimList(a.(*v1alpha1.BlockDeviceClaimList), b.(*openebsio.BlockDeviceClaimList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openebsio.BlockDeviceClaimList)(nil), (*v1alpha1.BlockDeviceClaimList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openebsio_BlockDeviceClaimList_To_v1alpha1_BlockDeviceClaimList(a.(*openebsio.BlockDeviceClaimList), b.(*v1alpha1.BlockDeviceClaimList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.BlockDeviceList)(nil), (*openebsio.BlockDeviceList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BlockDeviceList_To_openebsio_BlockDeviceList(a.(*v1alpha1.BlockDeviceList), b.(*openebsio.BlockDeviceList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openebsio.BlockDeviceList)(nil), (*v1alpha1.BlockDeviceList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openebsio_BlockDeviceList_To_v1alpha1_BlockDeviceList(a.(*openebsio.BlockDeviceList), b.(*v1alpha1.BlockDeviceList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.BlockDeviceNodeAttributes)(nil), (*openebsio.BlockDeviceNodeAttributes)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BlockDeviceNodeAttributes_To_openebsio_BlockDeviceNodeAttributes(a.(*v1alpha1.BlockDeviceNodeAttributes), b.(*openebsio.BlockDeviceNodeAttributes), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openebsio.BlockDeviceNodeAttributes)(nil), (*v1alpha1.BlockDeviceNodeAttributes)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openebsio_BlockDeviceNodeAttributes_To_v1alpha1_BlockDeviceNodeAttributes(a.(*openebsio.BlockDeviceNodeAttributes), b.(*v1alpha1.BlockDeviceNodeAttributes), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.CStorPool)(nil), (*openebsio.CStorPool)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CStorPool_To_openebsio_CStorPool(a.(*v1alpha1.CStorPool), b.(*openebsio.CStorPool), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openebsio.CStorPool)(nil), (*v1alpha1.CStorPool)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openebsio_CStorPool_To_v1alpha1_CStorPool(a.(*openebsio.CStorPool), b.(*v1alpha1.CStorPool), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.CStorPoolCluster)(nil), (*openebsio.CStorPoolCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CStorPoolCluster_To_openebsio_CStorPoolCluster(a.(*v1alpha1.CStorPoolCluster), b.(*openebsio.CStorPoolCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openebsio.CStorPoolCluster)(nil), (*v1alpha1.CStorPoolCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openebsio_CStorPoolCluster_To_v1alpha1_CStorPoolCluster(a.(*openebsio.CStorPoolCluster), b.(*v1alpha1.CStorPoolCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.CStorPoolInstance)(nil), (*openebsio.CStorPoolInstance)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CStorPoolInstance_To_openebsio_CStorPoolInstance(a.(*v1alpha1.CStorPoolInstance), b.(*openebsio.CStorPoolInstance), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openebsio.CStorPoolInstance)(nil), (*v1alpha1.CStorPoolInstance)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openebsio_CStorPoolInstance_To_v1alpha1_CStorPoolInstance(a.(*openebsio.CStorPoolInstance), b.(*v1alpha1.CStorPoolInstance), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.CStorVolume)(nil), (*openebsio.CStorVolume)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CStorVolume_To_openebsio_CStorVolume(a.(*v1alpha1.CStorVolume), b.(*openebsio.CStorVolume), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openebsio.CStorVolume)(nil), (*v1alpha1.CStorVolume)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openebsio_CStorVolume_To_v1alpha1_CStorVolume(a.(*openebsio.CStorVolume), b.(*v1alpha1.CStorVolume), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.DeviceCapacity)(nil), (*openebsio.DeviceCapacity)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DeviceCapacity_To_openebsio_DeviceCapacity(a.(*v1alpha1.DeviceCapacity), b.(*openebsio.DeviceCapacity), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openebsio.DeviceCapacity)(nil), (*v1alpha1.DeviceCapacity)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openebsio_DeviceCapacity_To_v1alpha1_DeviceCapacity(a.(*openebsio.DeviceCapacity), b.(*v1alpha1.DeviceCapacity), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.DeviceClaimDetails)(nil), (*openebsio.DeviceClaimDetails)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DeviceClaimDetails_To_openebsio_DeviceClaimDetails(a.(*v1alpha1.DeviceClaimDetails), b.(*openebsio.DeviceClaimDetails), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openebsio.DeviceClaimDetails)(nil), (*v1alpha1.DeviceClaimDetails)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openebsio_DeviceClaimDetails_To_v1alpha1_DeviceClaimDetails(a.(*openebsio.DeviceClaimDetails), b.(*v1alpha1.DeviceClaimDetails), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.DeviceClaimResources)(nil), (*openebsio.DeviceClaimResources)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DeviceClaimResources_To_openebsio_DeviceClaimResources(a.(*v1alpha1.DeviceClaimResources), b.(*openebsio.DeviceClaimResources), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openebsio.DeviceClaimResources)(nil), (*v1alpha1.DeviceClaimResources)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openebsio_DeviceClaimResources_To_v1alpha1_DeviceClaimResources(a.(*openebsio.DeviceClaimResources), b.(*v1alpha1.DeviceClaimResources), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.DeviceClaimSpec)(nil), (*openebsio.DeviceClaimSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DeviceClaimSpec_To_openebsio_DeviceClaimSpec(a.(*v1alpha1.DeviceClaimSpec), b.(*openebsio.DeviceClaimSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openebsio.DeviceClaimSpec)(nil), (*v1alpha1.DeviceClaimSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openebsio_DeviceClaimSpec_To_v1alpha1_DeviceClaimSpec(a.(*openebsio.DeviceClaimSpec), b.(*v1alpha1.DeviceClaimSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.DeviceClaimStatus)(nil), (*openebsio.DeviceClaimStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DeviceClaimStatus_To_openebsio_DeviceClaimStatus(a.(*v1alpha1.DeviceClaimStatus), b.(*openebsio.DeviceClaimStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openebsio.DeviceClaimStatus)(nil), (*v1alpha1.DeviceClaimStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openebsio_DeviceClaimStatus_To_v1alpha1_DeviceClaimStatus(a.(*openebsio.DeviceClaimStatus), b.(*v1alpha1.DeviceClaimStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.DeviceDetails)(nil), (*openebsio.DeviceDetails)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DeviceDetails_To_openebsio_DeviceDetails(a.(*v1alpha1.DeviceDetails), b.(*openebsio.DeviceDetails), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openebsio.DeviceDetails)(nil), (*v1alpha1.DeviceDetails)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openebsio_DeviceDetails_To_v1alpha1_DeviceDetails(a.(*openebsio.DeviceDetails), b.(*v1alpha1.DeviceDetails), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.DeviceDevLink)(nil), (*openebsio.DeviceDevLink)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DeviceDevLink_To_openebsio_DeviceDevLink(a.(*v1alpha1.DeviceDevLink), b.(*openebsio.DeviceDevLink), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openebsio.DeviceDevLink)(nil), (*v1alpha1.DeviceDevLink)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openebsio_DeviceDevLink_To_v1alpha1_DeviceDevLink(a.(*openebsio.DeviceDevLink), b.(*v1alpha1.DeviceDevLink), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.DeviceSpec)(nil), (*openebsio.DeviceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DeviceSpec_To_openebsio_DeviceSpec(a.(*v1alpha1.DeviceSpec), b.(*openebsio.DeviceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openebsio.DeviceSpec)(nil), (*v1alpha1.DeviceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openebsio_DeviceSpec_To_v1alpha1_DeviceSpec(a.(*openebsio.DeviceSpec), b.(*v1alpha1.DeviceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.DeviceStatus)(nil), (*openebsio.DeviceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DeviceStatus_To_openebsio_DeviceStatus(a.(*v1alpha1.DeviceStatus), b.(*openebsio.DeviceStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openebsio.DeviceStatus)(nil), (*v1alpha1.DeviceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openebsio_DeviceStatus_To_v1alpha1_DeviceStatus(a.(*openebsio.DeviceStatus), b.(*v1alpha1.DeviceStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.FileSystemInfo)(nil), (*openebsio.FileSystemInfo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_FileSystemInfo_To_openebsio_FileSystemInfo(a.(*v1alpha1.FileSystemInfo), b.(*openebsio.FileSystemInfo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openebsio.FileSystemInfo)(nil), (*v1alpha1.FileSystemInfo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openebsio_FileSystemInfo_To_v1alpha1_FileSystemInfo(a.(*openebsio.FileSystemInfo), b.(*v1alpha1.FileSystemInfo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.JivaVolume)(nil), (*openebsio.JivaVolume)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_JivaVolume_To_openebsio_JivaVolume(a.(*v1alpha1.JivaVolume), b.(*openebsio.JivaVolume), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openebsio.JivaVolume)(nil), (*v1alpha1.JivaVolume)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openebsio_JivaVolume_To_v1alpha1_JivaVolume(a.(*openebsio.JivaVolume), b.(*v1alpha1.JivaVolume), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.NodeAttribute)(nil), (*openebsio.NodeAttribute)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NodeAttribute_To_openebsio_NodeAttribute(a.(*v1alpha1.NodeAttribute), b.(*openebsio.NodeAttribute), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openebsio.NodeAttribute)(nil), (*v1alpha1.NodeAttribute)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openebsio_NodeAttribute_To_v1alpha1_NodeAttribute(a.(*openebsio.NodeAttribute), b.(*v1alpha1.NodeAttribute), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.Options)(nil), (*openebsio.Options)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Options_To_openebsio_Options(a.(*v1alpha1.Options), b.(*openebsio.Options), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openebsio.Options)(nil), (*v1alpha1.Options)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openebsio_Options_To_v1alpha1_Options(a.(*openebsio.Options), b.(*v1alpha1.Options), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.ResourceOptions)(nil), (*openebsio.ResourceOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ResourceOptions_To_openebsio_ResourceOptions(a.(*v1alpha1.ResourceOptions), b.(*openebsio.ResourceOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openebsio.ResourceOptions)(nil), (*v1alpha1.ResourceOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openebsio_ResourceOptions_To_v1alpha1_ResourceOptions(a.(*openebsio.ResourceOptions), b.(*v1alpha1.ResourceOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.ResourceSpec)(nil), (*openebsio.ResourceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ResourceSpec_To_openebsio_ResourceSpec(a.(*v1alpha1.ResourceSpec), b.(*openebsio.ResourceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openebsio.ResourceSpec)(nil), (*v1alpha1.ResourceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openebsio_ResourceSpec_To_v1alpha1_ResourceSpec(a.(*openebsio.ResourceSpec), b.(*v1alpha1.ResourceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.Status)(nil), (*openebsio.Status)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Status_To_openebsio_Status(a.(*v1alpha1.Status), b.(*openebsio.Status), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openebsio.Status)(nil), (*v1alpha1.Status)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openebsio_Status_To_v1alpha1_Status(a.(*openebsio.Status), b.(*v1alpha1.Status), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.StoragePoolClaim)(nil), (*openebsio.StoragePoolClaim)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_StoragePoolClaim_To_openebsio_StoragePoolClaim(a.(*v1alpha1.StoragePoolClaim), b.(*openebsio.StoragePoolClaim), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openebsio.StoragePoolClaim)(nil), (*v1alpha1.StoragePoolClaim)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openebsio_StoragePoolClaim_To_v1alpha1_StoragePoolClaim(a.(*openebsio.StoragePoolClaim), b.(*v1alpha1.StoragePoolClaim), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.UpgradeDetailedStatuses)(nil), (*openebsio.UpgradeDetailedStatuses)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_UpgradeDetailedStatuses_To_openebsio_UpgradeDetailedStatuses(a.(*v1alpha1.UpgradeDetailedStatuses), b.(*openebsio.UpgradeDetailedStatuses), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openebsio.UpgradeDetailedStatuses)(nil), (*v1alpha1.UpgradeDetailedStatuses)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openebsio_UpgradeDetailedStatuses_To_v1alpha1_UpgradeDetailedStatuses(a.(*openebsio.UpgradeDetailedStatuses), b.(*v1alpha1.UpgradeDetailedStatuses), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.UpgradeTask)(nil), (*openebsio.UpgradeTask)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_UpgradeTask_To_openebsio_UpgradeTask(a.(*v1alpha1.UpgradeTask), b.(*openebsio.UpgradeTask), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openebsio.UpgradeTask)(nil), (*v1alpha1.UpgradeTask)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openebsio_UpgradeTask_To_v1alpha1_UpgradeTask(a.(*openebsio.UpgradeTask), b.(*v1alpha1.UpgradeTask), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.UpgradeTaskList)(nil), (*openebsio.UpgradeTaskList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_UpgradeTaskList_To_openebsio_UpgradeTaskList(a.(*v1alpha1.UpgradeTaskList), b.(*openebsio.UpgradeTaskList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openebsio.UpgradeTaskList)(nil), (*v1alpha1.UpgradeTaskList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openebsio_UpgradeTaskList_To_v1alpha1_UpgradeTaskList(a.(*openebsio.UpgradeTaskList), b.(*v1alpha1.UpgradeTaskList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.UpgradeTaskSpec)(nil), (*openebsio.UpgradeTaskSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_UpgradeTaskSpec_To_openebsio_UpgradeTaskSpec(a.(*v1alpha1.UpgradeTaskSpec), b.(*openebsio.UpgradeTaskSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openebsio.UpgradeTaskSpec)(nil), (*v1alpha1.UpgradeTaskSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openebsio_UpgradeTaskSpec_To_v1alpha1_UpgradeTaskSpec(a.(*openebsio.UpgradeTaskSpec), b.(*v1alpha1.UpgradeTaskSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.UpgradeTaskStatus)(nil), (*openebsio.UpgradeTaskStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_UpgradeTaskStatus_To_openebsio_UpgradeTaskStatus(a.(*v1alpha1.UpgradeTaskStatus), b.(*openebsio.UpgradeTaskStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openebsio.UpgradeTaskStatus)(nil), (*v1alpha1.UpgradeTaskStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openebsio_UpgradeTaskStatus_To_v1alpha1_UpgradeTaskStatus(a.(*openebsio.UpgradeTaskStatus), b.(*v1alpha1.UpgradeTaskStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_BlockDevice_To_openebsio_BlockDevice(in *v1alpha1.BlockDevice, out *openebsio.BlockDevice, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_DeviceSpec_To_openebsio_DeviceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_DeviceStatus_To_openebsio_DeviceStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_BlockDevice_To_openebsio_BlockDevice is an autogenerated conversion function.
func Convert_v1alpha1_BlockDevice_To_openebsio_BlockDevice(in *v1alpha1.BlockDevice, out *openebsio.BlockDevice, s conversion.Scope) error {
	return autoConvert_v1alpha1_BlockDevice_To_openebsio_BlockDevice(in, out, s)
}

func autoConvert_openebsio_BlockDevice_To_v1alpha1_BlockDevice(in *openebsio.BlockDevice, out *v1alpha1.BlockDevice, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_openebsio_DeviceSpec_To_v1alpha1_DeviceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_openebsio_DeviceStatus_To_v1alpha1_DeviceStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_openebsio_BlockDevice_To_v1alpha1_BlockDevice is an autogenerated conversion function.
func Convert_openebsio_BlockDevice_To_v1alpha1_BlockDevice(in *openebsio.BlockDevice, out *v1alpha1.BlockDevice, s conversion.Scope) error {
	return autoConvert_openebsio_BlockDevice_To_v1alpha1_BlockDevice(in, out, s)
}

func autoConvert_v1alpha1_BlockDeviceClaim_To_openebsio_BlockDeviceClaim(in *v1alpha1.BlockDeviceClaim, out *openebsio.BlockDeviceClaim, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_DeviceClaimSpec_To_openebsio_DeviceClaimSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_DeviceClaimStatus_To_openebsio_DeviceClaimStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_BlockDeviceClaim_To_openebsio_BlockDeviceClaim is an autogenerated conversion function.
func Convert_v1alpha1_BlockDeviceClaim_To_openebsio_BlockDeviceClaim(in *v1alpha1.BlockDeviceClaim, out *openebsio.BlockDeviceClaim, s conversion.Scope) error {
	return autoConvert_v1alpha1_BlockDeviceClaim_To_openebsio_BlockDeviceClaim(in, out, s)
}

func autoConvert_openebsio_BlockDeviceClaim_To_v1alpha1_BlockDeviceClaim(in *openebsio.BlockDeviceClaim, out *v1alpha1.BlockDeviceClaim, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_openebsio_DeviceClaimSpec_To_v1alpha1_DeviceClaimSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_openebsio_DeviceClaimStatus_To_v1alpha1_DeviceClaimStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_openebsio_BlockDeviceClaim_To_v1alpha1_BlockDeviceClaim is an autogenerated conversion function.
func Convert_openebsio_BlockDeviceClaim_To_v1alpha1_BlockDeviceClaim(in *openebsio.BlockDeviceClaim, out *v1alpha1.BlockDeviceClaim, s conversion.Scope) error {
	return autoConvert_openebsio_BlockDeviceClaim_To_v1alpha1_BlockDeviceClaim(in, out, s)
}

func autoConvert_v1alpha1_BlockDeviceClaimList_To_openebsio_BlockDeviceClaimList(in *v1alpha1.BlockDeviceClaimList, out *openebsio.BlockDeviceClaimList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]openebsio.BlockDeviceClaim)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_BlockDeviceClaimList_To_openebsio_BlockDeviceClaimList is an autogenerated conversion function.
func Convert_v1alpha1_BlockDeviceClaimList_To_openebsio_BlockDeviceClaimList(in *v1alpha1.BlockDeviceClaimList, out *openebsio.BlockDeviceClaimList, s conversion.Scope) error {
	return autoConvert_v1alpha1_BlockDeviceClaimList_To_openebsio_BlockDeviceClaimList(in, out, s)
}

func autoConvert_openebsio_BlockDeviceClaimList_To_v1alpha1_BlockDeviceClaimList(in *openebsio.BlockDeviceClaimList, out *v1alpha1.BlockDeviceClaimList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1alpha1.BlockDeviceClaim)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_openebsio_BlockDeviceClaimList_To_v1alpha1_BlockDeviceClaimList is an autogenerated conversion function.
func Convert_openebsio_BlockDeviceClaimList_To_v1alpha1_BlockDeviceClaimList(in *openebsio.BlockDeviceClaimList, out *v1alpha1.BlockDeviceClaimList, s conversion.Scope) error {
	return autoConvert_openebsio_BlockDeviceClaimList_To_v1alpha1_BlockDeviceClaimList(in, out, s)
}

func autoConvert_v1alpha1_BlockDeviceList_To_openebsio_BlockDeviceList(in *v1alpha1.BlockDeviceList, out *openebsio.BlockDeviceList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]openebsio.BlockDevice)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_BlockDeviceList_To_openebsio_BlockDeviceList is an autogenerated conversion function.
func Convert_v1alpha1_BlockDeviceList_To_openebsio_BlockDeviceList(in *v1alpha1.BlockDeviceList, out *openebsio.BlockDeviceList, s conversion.Scope) error {
	return autoConvert_v1alpha1_BlockDeviceList_To_openebsio_BlockDeviceList(in, out, s)
}

func autoConvert_openebsio_BlockDeviceList_To_v1alpha1_BlockDeviceList(in *openebsio.BlockDeviceList, out *v1alpha1.BlockDeviceList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1alpha1.BlockDevice)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_openebsio_BlockDeviceList_To_v1alpha1_BlockDeviceList is an autogenerated conversion function.
func Convert_openebsio_BlockDeviceList_To_v1alpha1_BlockDeviceList(in *openebsio.BlockDeviceList, out *v1alpha1.BlockDeviceList, s conversion.Scope) error {
	return autoConvert_openebsio_BlockDeviceList_To_v1alpha1_BlockDeviceList(in, out, s)
}

func autoConvert_v1alpha1_BlockDeviceNodeAttributes_To_openebsio_BlockDeviceNodeAttributes(in *v1alpha1.BlockDeviceNodeAttributes, out *openebsio.BlockDeviceNodeAttributes, s conversion.Scope) error {
	out.NodeName = in.NodeName
	out.HostName = in.HostName
	return nil
}

// Convert_v1alpha1_BlockDeviceNodeAttributes_To_openebsio_BlockDeviceNodeAttributes is an autogenerated conversion function.
func Convert_v1alpha1_BlockDeviceNodeAttributes_To_openebsio_BlockDeviceNodeAttributes(in *v1alpha1.BlockDeviceNodeAttributes, out *openebsio.BlockDeviceNodeAttributes, s conversion.Scope) error {
	return autoConvert_v1alpha1_BlockDeviceNodeAttributes_To_openebsio_BlockDeviceNodeAttributes(in, out, s)
}

func autoConvert_openebsio_BlockDeviceNodeAttributes_To_v1alpha1_BlockDeviceNodeAttributes(in *openebsio.BlockDeviceNodeAttributes, out *v1alpha1.BlockDeviceNodeAttributes, s conversion.Scope) error {
	out.NodeName = in.NodeName
	out.HostName = in.HostName
	return nil
}

// Convert_openebsio_BlockDeviceNodeAttributes_To_v1alpha1_BlockDeviceNodeAttributes is an autogenerated conversion function.
func Convert_openebsio_BlockDeviceNodeAttributes_To_v1alpha1_BlockDeviceNodeAttributes(in *openebsio.BlockDeviceNodeAttributes, out *v1alpha1.BlockDeviceNodeAttributes, s conversion.Scope) error {
	return autoConvert_openebsio_BlockDeviceNodeAttributes_To_v1alpha1_BlockDeviceNodeAttributes(in, out, s)
}

func autoConvert_v1alpha1_CStorPool_To_openebsio_CStorPool(in *v1alpha1.CStorPool, out *openebsio.CStorPool, s conversion.Scope) error {
	out.PoolName = in.PoolName
	out.Options = (*openebsio.ResourceOptions)(unsafe.Pointer(in.Options))
	return nil
}

// Convert_v1alpha1_CStorPool_To_openebsio_CStorPool is an autogenerated conversion function.
func Convert_v1alpha1_CStorPool_To_openebsio_CStorPool(in *v1alpha1.CStorPool, out *openebsio.CStorPool, s conversion.Scope) error {
	return autoConvert_v1alpha1_CStorPool_To_openebsio_CStorPool(in, out, s)
}

func autoConvert_openebsio_CStorPool_To_v1alpha1_CStorPool(in *openebsio.CStorPool, out *v1alpha1.CStorPool, s conversion.Scope) error {
	out.PoolName = in.PoolName
	out.Options = (*v1alpha1.ResourceOptions)(unsafe.Pointer(in.Options))
	return nil
}

// Convert_openebsio_CStorPool_To_v1alpha1_CStorPool is an autogenerated conversion function.
func Convert_openebsio_CStorPool_To_v1alpha1_CStorPool(in *openebsio.CStorPool, out *v1alpha1.CStorPool, s conversion.Scope) error {
	return autoConvert_openebsio_CStorPool_To_v1alpha1_CStorPool(in, out, s)
}

func autoConvert_v1alpha1_CStorPoolCluster_To_openebsio_CStorPoolCluster(in *v1alpha1.CStorPoolCluster, out *openebsio.CStorPoolCluster, s conversion.Scope) error {
	out.CSPCName = in.CSPCName
	out.Options = (*openebsio.ResourceOptions)(unsafe.Pointer(in.Options))
	return nil
}

// Convert_v1alpha1_CStorPoolCluster_To_openebsio_CStorPoolCluster is an autogenerated conversion function.
func Convert_v1alpha1_CStorPoolCluster_To_openebsio_CStorPoolCluster(in *v1alpha1.CStorPoolCluster, out *openebsio.CStorPoolCluster, s conversion.Scope) error {
	return autoConvert_v1alpha1_CStorPoolCluster_To_openebsio_CStorPoolCluster(in, out, s)
}

func autoConvert_openebsio_CStorPoolCluster_To_v1alpha1_CStorPoolCluster(in *openebsio.CStorPoolCluster, out *v1alpha1.CStorPoolCluster, s conversion.Scope) error {
	out.CSPCName = in.CSPCName
	out.Options = (*v1alpha1.ResourceOptions)(unsafe.Pointer(in.Options))
	return nil
}

// Convert_openebsio_CStorPoolCluster_To_v1alpha1_CStorPoolCluster is an autogenerated conversion function.
func Convert_openebsio_CStorPoolCluster_To_v1alpha1_CStorPoolCluster(in *openebsio.CStorPoolCluster, out *v1alpha1.CStorPoolCluster, s conversion.Scope) error {
	return autoConvert_openebsio_CStorPoolCluster_To_v1alpha1_CStorPoolCluster(in, out, s)
}

func autoConvert_v1alpha1_CStorPoolInstance_To_openebsio_CStorPoolInstance(in *v1alpha1.CStorPoolInstance, out *openebsio.CStorPoolInstance, s conversion.Scope) error {
	out.CSPIName = in.CSPIName
	out.Options = (*openebsio.ResourceOptions)(unsafe.Pointer(in.Options))
	return nil
}

// Convert_v1alpha1_CStorPoolInstance_To_openebsio_CStorPoolInstance is an autogenerated conversion function.
func Convert_v1alpha1_CStorPoolInstance_To_openebsio_CStorPoolInstance(in *v1alpha1.CStorPoolInstance, out *openebsio.CStorPoolInstance, s conversion.Scope) error {
	return autoConvert_v1alpha1_CStorPoolInstance_To_openebsio_CStorPoolInstance(in, out, s)
}

func autoConvert_openebsio_CStorPoolInstance_To_v1alpha1_CStorPoolInstance(in *openebsio.CStorPoolInstance, out *v1alpha1.CStorPoolInstance, s conversion.Scope) error {
	out.CSPIName = in.CSPIName
	out.Options = (*v1alpha1.ResourceOptions)(unsafe.Pointer(in.Options))
	return nil
}

// Convert_openebsio_CStorPoolInstance_To_v1alpha1_CStorPoolInstance is an autogenerated conversion function.
func Convert_openebsio_CStorPoolInstance_To_v1alpha1_CStorPoolInstance(in *openebsio.CStorPoolInstance, out *v1alpha1.CStorPoolInstance, s conversion.Scope) error {
	return autoConvert_openebsio_CStorPoolInstance_To_v1alpha1_CStorPoolInstance(in, out, s)
}

func autoConvert_v1alpha1_CStorVolume_To_openebsio_CStorVolume(in *v1alpha1.CStorVolume, out *openebsio.CStorVolume, s conversion.Scope) error {
	out.PVName = in.PVName
	out.Options = (*openebsio.ResourceOptions)(unsafe.Pointer(in.Options))
	return nil
}

// Convert_v1alpha1_CStorVolume_To_openebsio_CStorVolume is an autogenerated conversion function.
func Convert_v1alpha1_CStorVolume_To_openebsio_CStorVolume(in *v1alpha1.CStorVolume, out *openebsio.CStorVolume, s conversion.Scope) error {
	return autoConvert_v1alpha1_CStorVolume_To_openebsio_CStorVolume(in, out, s)
}

func autoConvert_openebsio_CStorVolume_To_v1alpha1_CStorVolume(in *openebsio.CStorVolume, out *v1alpha1.CStorVolume, s conversion.Scope) error {
	out.PVName = in.PVName
	out.Options = (*v1alpha1.ResourceOptions)(unsafe.Pointer(in.Options))
	return nil
}

// Convert_openebsio_CStorVolume_To_v1alpha1_CStorVolume is an autogenerated conversion function.
func Convert_openebsio_CStorVolume_To_v1alpha1_CStorVolume(in *openebsio.CStorVolume, out *v1alpha1.CStorVolume, s conversion.Scope) error {
	return autoConvert_openebsio_CStorVolume_To_v1alpha1_CStorVolume(in, out, s)
}

func autoConvert_v1alpha1_DeviceCapacity_To_openebsio_DeviceCapacity(in *v1alpha1.DeviceCapacity, out *openebsio.DeviceCapacity, s conversion.Scope) error {
	out.Storage = in.Storage
	out.PhysicalSectorSize = in.PhysicalSectorSize
	out.LogicalSectorSize = in.LogicalSectorSize
	return nil
}

// Convert_v1alpha1_DeviceCapacity_To_openebsio_DeviceCapacity is an autogenerated conversion function.
func Convert_v1alpha1_DeviceCapacity_To_openebsio_DeviceCapacity(in *v1alpha1.DeviceCapacity, out *openebsio.DeviceCapacity, s conversion.Scope) error {
	return autoConvert_v1alpha1_DeviceCapacity_To_openebsio_DeviceCapacity(in, out, s)
}

func autoConvert_openebsio_DeviceCapacity_To_v1alpha1_DeviceCapacity(in *openebsio.DeviceCapacity, out *v1alpha1.DeviceCapacity, s conversion.Scope) error {
	out.Storage = in.Storage
	out.PhysicalSectorSize = in.PhysicalSectorSize
	out.LogicalSectorSize = in.LogicalSectorSize
	return nil
}

// Convert_openebsio_DeviceCapacity_To_v1alpha1_DeviceCapacity is an autogenerated conversion function.
func Convert_openebsio_DeviceCapacity_To_v1alpha1_DeviceCapacity(in *openebsio.DeviceCapacity, out *v1alpha1.DeviceCapacity, s conversion.Scope) error {
	return autoConvert_openebsio_DeviceCapacity_To_v1alpha1_DeviceCapacity(in, out, s)
}

func autoConvert_v1alpha1_DeviceClaimDetails_To_openebsio_DeviceClaimDetails(in *v1alpha1.DeviceClaimDetails, out *openebsio.DeviceClaimDetails, s conversion.Scope) error {
	out.BlockVolumeMode = openebsio.BlockDeviceVolumeMode(in.BlockVolumeMode)
	out.DeviceFormat = in.DeviceFormat
	out.AllowPartition = in.AllowPartition
	return nil
}

// Convert_v1alpha1_DeviceClaimDetails_To_openebsio_DeviceClaimDetails is an autogenerated conversion function.
func Convert_v1alpha1_DeviceClaimDetails_To_openebsio_DeviceClaimDetails(in *v1alpha1.DeviceClaimDetails, out *openebsio.DeviceClaimDetails, s conversion.Scope) error {
	return autoConvert_v1alpha1_DeviceClaimDetails_To_openebsio_DeviceClaimDetails(in, out, s)
}

func autoConvert_openebsio_DeviceClaimDetails_To_v1alpha1_DeviceClaimDetails(in *openebsio.DeviceClaimDetails, out *v1alpha1.DeviceClaimDetails, s conversion.Scope) error {
	out.BlockVolumeMode = v1alpha1.BlockDeviceVolumeMode(in.BlockVolumeMode)
	out.DeviceFormat = in.DeviceFormat
	out.AllowPartition = in.AllowPartition
	return nil
}

// Convert_openebsio_DeviceClaimDetails_To_v1alpha1_DeviceClaimDetails is an autogenerated conversion function.
func Convert_openebsio_DeviceClaimDetails_To_v1alpha1_DeviceClaimDetails(in *openebsio.DeviceClaimDetails, out *v1alpha1.DeviceClaimDetails, s conversion.Scope) error {
	return autoConvert_openebsio_DeviceClaimDetails_To_v1alpha1_DeviceClaimDetails(in, out, s)
}

func autoConvert_v1alpha1_DeviceClaimResources_To_openebsio_DeviceClaimResources(in *v1alpha1.DeviceClaimResources, out *openebsio.DeviceClaimResources, s conversion.Scope) error {
	out.Requests = *(*v1.ResourceList)(unsafe.Pointer(&in.Requests))
	return nil
}

// Convert_v1alpha1_DeviceClaimResources_To_openebsio_DeviceClaimResources is an autogenerated conversion function.
func Convert_v1alpha1_DeviceClaimResources_To_openebsio_DeviceClaimResources(in *v1alpha1.DeviceClaimResources, out *openebsio.DeviceClaimResources, s conversion.Scope) error {
	return autoConvert_v1alpha1_DeviceClaimResources_To_openebsio_DeviceClaimResources(in, out, s)
}

func autoConvert_openebsio_DeviceClaimResources_To_v1alpha1_DeviceClaimResources(in *openebsio.DeviceClaimResources, out *v1alpha1.DeviceClaimResources, s conversion.Scope) error {
	out.Requests = *(*v1.ResourceList)(unsafe.Pointer(&in.Requests))
	return nil
}

// Convert_openebsio_DeviceClaimResources_To_v1alpha1_DeviceClaimResources is an autogenerated conversion function.
func Convert_openebsio_DeviceClaimResources_To_v1alpha1_DeviceClaimResources(in *openebsio.DeviceClaimResources, out *v1alpha1.DeviceClaimResources, s conversion.Scope) error {
	return autoConvert_openebsio_DeviceClaimResources_To_v1alpha1_DeviceClaimResources(in, out, s)
}

func autoConvert_v1alpha1_DeviceClaimSpec_To_openebsio_DeviceClaimSpec(in *v1alpha1.DeviceClaimSpec, out *openebsio.DeviceClaimSpec, s conversion.Scope) error {
	out.Selector = (*metav1.LabelSelector)(unsafe.Pointer(in.Selector))
	if err := Convert_v1alpha1_DeviceClaimResources_To_openebsio_DeviceClaimResources(&in.Resources, &out.Resources, s); err != nil {
		return err
	}
	out.DeviceType = in.DeviceType
	out.HostName = in.HostName
	if err := Convert_v1alpha1_DeviceClaimDetails_To_openebsio_DeviceClaimDetails(&in.Details, &out.Details, s); err != nil {
		return err
	}
	out.BlockDeviceName = in.BlockDeviceName
	if err := Convert_v1alpha1_BlockDeviceNodeAttributes_To_openebsio_BlockDeviceNodeAttributes(&in.BlockDeviceNodeAttributes, &out.BlockDeviceNodeAttributes, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_DeviceClaimSpec_To_openebsio_DeviceClaimSpec is an autogenerated conversion function.
func Convert_v1alpha1_DeviceClaimSpec_To_openebsio_DeviceClaimSpec(in *v1alpha1.DeviceClaimSpec, out *openebsio.DeviceClaimSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_DeviceClaimSpec_To_openebsio_DeviceClaimSpec(in, out, s)
}

func autoConvert_openebsio_DeviceClaimSpec_To_v1alpha1_DeviceClaimSpec(in *openebsio.DeviceClaimSpec, out *v1alpha1.DeviceClaimSpec, s conversion.Scope) error {
	out.Selector = (*metav1.LabelSelector)(unsafe.Pointer(in.Selector))
	if err := Convert_openebsio_DeviceClaimResources_To_v1alpha1_DeviceClaimResources(&in.Resources, &out.Resources, s); err != nil {
		return err
	}
	out.DeviceType = in.DeviceType
	out.HostName = in.HostName
	if err := Convert_openebsio_DeviceClaimDetails_To_v1alpha1_DeviceClaimDetails(&in.Details, &out.Details, s); err != nil {
		return err
	}
	out.BlockDeviceName = in.BlockDeviceName
	if err := Convert_openebsio_BlockDeviceNodeAttributes_To_v1alpha1_BlockDeviceNodeAttributes(&in.BlockDeviceNodeAttributes, &out.BlockDeviceNodeAttributes, s); err != nil {
		return err
	}
	return nil
}

// Convert_openebsio_DeviceClaimSpec_To_v1alpha1_DeviceClaimSpec is an autogenerated conversion function.
func Convert_openebsio_DeviceClaimSpec_To_v1alpha1_DeviceClaimSpec(in *openebsio.DeviceClaimSpec, out *v1alpha1.DeviceClaimSpec, s conversion.Scope) error {
	return autoConvert_openebsio_DeviceClaimSpec_To_v1alpha1_DeviceClaimSpec(in, out, s)
}

func autoConvert_v1alpha1_DeviceClaimStatus_To_openebsio_DeviceClaimStatus(in *v1alpha1.DeviceClaimStatus, out *openebsio.DeviceClaimStatus, s conversion.Scope) error {
	out.Phase = openebsio.DeviceClaimPhase(in.Phase)
	return nil
}

// Convert_v1alpha1_DeviceClaimStatus_To_openebsio_DeviceClaimStatus is an autogenerated conversion function.
func Convert_v1alpha1_DeviceClaimStatus_To_openebsio_DeviceClaimStatus(in *v1alpha1.DeviceClaimStatus, out *openebsio.DeviceClaimStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_DeviceClaimStatus_To_openebsio_DeviceClaimStatus(in, out, s)
}

func autoConvert_openebsio_DeviceClaimStatus_To_v1alpha1_DeviceClaimStatus(in *openebsio.DeviceClaimStatus, out *v1alpha1.DeviceClaimStatus, s conversion.Scope) error {
	out.Phase = v1alpha1.DeviceClaimPhase(in.Phase)
	return nil
}

// Convert_openebsio_DeviceClaimStatus_To_v1alpha1_DeviceClaimStatus is an autogenerated conversion function.
func Convert_openebsio_DeviceClaimStatus_To_v1alpha1_DeviceClaimStatus(in *openebsio.DeviceClaimStatus, out *v1alpha1.DeviceClaimStatus, s conversion.Scope) error {
	return autoConvert_openebsio_DeviceClaimStatus_To_v1alpha1_DeviceClaimStatus(in, out, s)
}

func autoConvert_v1alpha1_DeviceDetails_To_openebsio_DeviceDetails(in *v1alpha1.DeviceDetails, out *openebsio.DeviceDetails, s conversion.Scope) error {
	out.DeviceType = in.DeviceType
	out.DriveType = in.DriveType
	out.LogicalBlockSize = in.LogicalBlockSize
	out.PhysicalBlockSize = in.PhysicalBlockSize
	out.HardwareSectorSize = in.HardwareSectorSize
	out.Model = in.Model
	out.Compliance = in.Compliance
	out.Serial = in.Serial
	out.Vendor = in.Vendor
	out.FirmwareRevision = in.FirmwareRevision
	return nil
}

// Convert_v1alpha1_DeviceDetails_To_openebsio_DeviceDetails is an autogenerated conversion function.
func Convert_v1alpha1_DeviceDetails_To_openebsio_DeviceDetails(in *v1alpha1.DeviceDetails, out *openebsio.DeviceDetails, s conversion.Scope) error {
	return autoConvert_v1alpha1_DeviceDetails_To_openebsio_DeviceDetails(in, out, s)
}

func autoConvert_openebsio_DeviceDetails_To_v1alpha1_DeviceDetails(in *openebsio.DeviceDetails, out *v1alpha1.DeviceDetails, s conversion.Scope) error {
	out.DeviceType = in.DeviceType
	out.DriveType = in.DriveType
	out.LogicalBlockSize = in.LogicalBlockSize
	out.PhysicalBlockSize = in.PhysicalBlockSize
	out.HardwareSectorSize = in.HardwareSectorSize
	out.Model = in.Model
	out.Compliance = in.Compliance
	out.Serial = in.Serial
	out.Vendor = in.Vendor
	out.FirmwareRevision = in.FirmwareRevision
	return nil
}

// Convert_openebsio_DeviceDetails_To_v1alpha1_DeviceDetails is an autogenerated conversion function.
func Convert_openebsio_DeviceDetails_To_v1alpha1_DeviceDetails(in *openebsio.DeviceDetails, out *v1alpha1.DeviceDetails, s conversion.Scope) error {
	return autoConvert_openebsio_DeviceDetails_To_v1alpha1_DeviceDetails(in, out, s)
}

func autoConvert_v1alpha1_DeviceDevLink_To_openebsio_DeviceDevLink(in *v1alpha1.DeviceDevLink, out *openebsio.DeviceDevLink, s conversion.Scope) error {
	out.Kind = in.Kind
	out.Links = *(*[]string)(unsafe.Pointer(&in.Links))
	return nil
}

// Convert_v1alpha1_DeviceDevLink_To_openebsio_DeviceDevLink is an autogenerated conversion function.
func Convert_v1alpha1_DeviceDevLink_To_openebsio_DeviceDevLink(in *v1alpha1.DeviceDevLink, out *openebsio.DeviceDevLink, s conversion.Scope) error {
	return autoConvert_v1alpha1_DeviceDevLink_To_openebsio_DeviceDevLink(in, out, s)
}

func autoConvert_openebsio_DeviceDevLink_To_v1alpha1_DeviceDevLink(in *openebsio.DeviceDevLink, out *v1alpha1.DeviceDevLink, s conversion.Scope) error {
	out.Kind = in.Kind
	out.Links = *(*[]string)(unsafe.Pointer(&in.Links))
	return nil
}

// Convert_openebsio_DeviceDevLink_To_v1alpha1_DeviceDevLink is an autogenerated conversion function.
func Convert_openebsio_DeviceDevLink_To_v1alpha1_DeviceDevLink(in *openebsio.DeviceDevLink, out *v1alpha1.DeviceDevLink, s conversion.Scope) error {
	return autoConvert_openebsio_DeviceDevLink_To_v1alpha1_DeviceDevLink(in, out, s)
}

func autoConvert_v1alpha1_DeviceSpec_To_openebsio_DeviceSpec(in *v1alpha1.DeviceSpec, out *openebsio.DeviceSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_NodeAttribute_To_openebsio_NodeAttribute(&in.NodeAttributes, &out.NodeAttributes, s); err != nil {
		return err
	}
	out.Path = in.Path
	if err := Convert_v1alpha1_DeviceCapacity_To_openebsio_DeviceCapacity(&in.Capacity, &out.Capacity, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_DeviceDetails_To_openebsio_DeviceDetails(&in.Details, &out.Details, s); err != nil {
		return err
	}
	out.ClaimRef = (*v1.ObjectReference)(unsafe.Pointer(in.ClaimRef))
	out.DevLinks = *(*[]openebsio.DeviceDevLink)(unsafe.Pointer(&in.DevLinks))
	if err := Convert_v1alpha1_FileSystemInfo_To_openebsio_FileSystemInfo(&in.FileSystem, &out.FileSystem, s); err != nil {
		return err
	}
	out.Partitioned = in.Partitioned
	out.ParentDevice = in.ParentDevice
	out.AggregateDevice = in.AggregateDevice
	return nil
}

// Convert_v1alpha1_DeviceSpec_To_openebsio_DeviceSpec is an autogenerated conversion function.
func Convert_v1alpha1_DeviceSpec_To_openebsio_DeviceSpec(in *v1alpha1.DeviceSpec, out *openebsio.DeviceSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_DeviceSpec_To_openebsio_DeviceSpec(in, out, s)
}

func autoConvert_openebsio_DeviceSpec_To_v1alpha1_DeviceSpec(in *openebsio.DeviceSpec, out *v1alpha1.DeviceSpec, s conversion.Scope) error {
	if err := Convert_openebsio_NodeAttribute_To_v1alpha1_NodeAttribute(&in.NodeAttributes, &out.NodeAttributes, s); err != nil {
		return err
	}
	out.Path = in.Path
	if err := Convert_openebsio_DeviceCapacity_To_v1alpha1_DeviceCapacity(&in.Capacity, &out.Capacity, s); err != nil {
		return err
	}
	if err := Convert_openebsio_DeviceDetails_To_v1alpha1_DeviceDetails(&in.Details, &out.Details, s); err != nil {
		return err
	}
	out.ClaimRef = (*v1.ObjectReference)(unsafe.Pointer(in.ClaimRef))
	out.DevLinks = *(*[]v1alpha1.DeviceDevLink)(unsafe.Pointer(&in.DevLinks))
	if err := Convert_openebsio_FileSystemInfo_To_v1alpha1_FileSystemInfo(&in.FileSystem, &out.FileSystem, s); err != nil {
		return err
	}
	out.Partitioned = in.Partitioned
	out.ParentDevice = in.ParentDevice
	out.AggregateDevice = in.AggregateDevice
	return nil
}

// Convert_openebsio_DeviceSpec_To_v1alpha1_DeviceSpec is an autogenerated conversion function.
func Convert_openebsio_DeviceSpec_To_v1alpha1_DeviceSpec(in *openebsio.DeviceSpec, out *v1alpha1.DeviceSpec, s conversion.Scope) error {
	return autoConvert_openebsio_DeviceSpec_To_v1alpha1_DeviceSpec(in, out, s)
}

func autoConvert_v1alpha1_DeviceStatus_To_openebsio_DeviceStatus(in *v1alpha1.DeviceStatus, out *openebsio.DeviceStatus, s conversion.Scope) error {
	out.ClaimState = openebsio.DeviceClaimState(in.ClaimState)
	out.State = openebsio.BlockDeviceState(in.State)
	return nil
}

// Convert_v1alpha1_DeviceStatus_To_openebsio_DeviceStatus is an autogenerated conversion function.
func Convert_v1alpha1_DeviceStatus_To_openebsio_DeviceStatus(in *v1alpha1.DeviceStatus, out *openebsio.DeviceStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_DeviceStatus_To_openebsio_DeviceStatus(in, out, s)
}

func autoConvert_openebsio_DeviceStatus_To_v1alpha1_DeviceStatus(in *openebsio.DeviceStatus, out *v1alpha1.DeviceStatus, s conversion.Scope) error {
	out.ClaimState = v1alpha1.DeviceClaimState(in.ClaimState)
	out.State = v1alpha1.BlockDeviceState(in.State)
	return nil
}

// Convert_openebsio_DeviceStatus_To_v1alpha1_DeviceStatus is an autogenerated conversion function.
func Convert_openebsio_DeviceStatus_To_v1alpha1_DeviceStatus(in *openebsio.DeviceStatus, out *v1alpha1.DeviceStatus, s conversion.Scope) error {
	return autoConvert_openebsio_DeviceStatus_To_v1alpha1_DeviceStatus(in, out, s)
}

func autoConvert_v1alpha1_FileSystemInfo_To_openebsio_FileSystemInfo(in *v1alpha1.FileSystemInfo, out *openebsio.FileSystemInfo, s conversion.Scope) error {
	out.Type = in.Type
	out.Mountpoint = in.Mountpoint
	return nil
}

// Convert_v1alpha1_FileSystemInfo_To_openebsio_FileSystemInfo is an autogenerated conversion function.
func Convert_v1alpha1_FileSystemInfo_To_openebsio_FileSystemInfo(in *v1alpha1.FileSystemInfo, out *openebsio.FileSystemInfo, s conversion.Scope) error {
	return autoConvert_v1alpha1_FileSystemInfo_To_openebsio_FileSystemInfo(in, out, s)
}

func autoConvert_openebsio_FileSystemInfo_To_v1alpha1_FileSystemInfo(in *openebsio.FileSystemInfo, out *v1alpha1.FileSystemInfo, s conversion.Scope) error {
	out.Type = in.Type
	out.Mountpoint = in.Mountpoint
	return nil
}

// Convert_openebsio_FileSystemInfo_To_v1alpha1_FileSystemInfo is an autogenerated conversion function.
func Convert_openebsio_FileSystemInfo_To_v1alpha1_FileSystemInfo(in *openebsio.FileSystemInfo, out *v1alpha1.FileSystemInfo, s conversion.Scope) error {
	return autoConvert_openebsio_FileSystemInfo_To_v1alpha1_FileSystemInfo(in, out, s)
}

func autoConvert_v1alpha1_JivaVolume_To_openebsio_JivaVolume(in *v1alpha1.JivaVolume, out *openebsio.JivaVolume, s conversion.Scope) error {
	out.PVName = in.PVName
	out.Options = (*openebsio.ResourceOptions)(unsafe.Pointer(in.Options))
	return nil
}

// Convert_v1alpha1_JivaVolume_To_openebsio_JivaVolume is an autogenerated conversion function.
func Convert_v1alpha1_JivaVolume_To_openebsio_JivaVolume(in *v1alpha1.JivaVolume, out *openebsio.JivaVolume, s conversion.Scope) error {
	return autoConvert_v1alpha1_JivaVolume_To_openebsio_JivaVolume(in, out, s)
}

func autoConvert_openebsio_JivaVolume_To_v1alpha1_JivaVolume(in *openebsio.JivaVolume, out *v1alpha1.JivaVolume, s conversion.Scope) error {
	out.PVName = in.PVName
	out.Options = (*v1alpha1.ResourceOptions)(unsafe.Pointer(in.Options))
	return nil
}

// Convert_openebsio_JivaVolume_To_v1alpha1_JivaVolume is an autogenerated conversion function.
func Convert_openebsio_JivaVolume_To_v1alpha1_JivaVolume(in *openebsio.JivaVolume, out *v1alpha1.JivaVolume, s conversion.Scope) error {
	return autoConvert_openebsio_JivaVolume_To_v1alpha1_JivaVolume(in, out, s)
}

func autoConvert_v1alpha1_NodeAttribute_To_openebsio_NodeAttribute(in *v1alpha1.NodeAttribute, out *openebsio.NodeAttribute, s conversion.Scope) error {
	out.NodeName = in.NodeName
	return nil
}

// Convert_v1alpha1_NodeAttribute_To_openebsio_NodeAttribute is an autogenerated conversion function.
func Convert_v1alpha1_NodeAttribute_To_openebsio_NodeAttribute(in *v1alpha1.NodeAttribute, out *openebsio.NodeAttribute, s conversion.Scope) error {
	return autoConvert_v1alpha1_NodeAttribute_To_openebsio_NodeAttribute(in, out, s)
}

func autoConvert_openebsio_NodeAttribute_To_v1alpha1_NodeAttribute(in *openebsio.NodeAttribute, out *v1alpha1.NodeAttribute, s conversion.Scope) error {
	out.NodeName = in.NodeName
	return nil
}

// Convert_openebsio_NodeAttribute_To_v1alpha1_NodeAttribute is an autogenerated conversion function.
func Convert_openebsio_NodeAttribute_To_v1alpha1_NodeAttribute(in *openebsio.NodeAttribute, out *v1alpha1.NodeAttribute, s conversion.Scope) error {
	return autoConvert_openebsio_NodeAttribute_To_v1alpha1_NodeAttribute(in, out, s)
}

func autoConvert_v1alpha1_Options_To_openebsio_Options(in *v1alpha1.Options, out *openebsio.Options, s conversion.Scope) error {
	out.Timeout = in.Timeout
	return nil
}

// Convert_v1alpha1_Options_To_openebsio_Options is an autogenerated conversion function.
func Convert_v1alpha1_Options_To_openebsio_Options(in *v1alpha1.Options, out *openebsio.Options, s conversion.Scope) error {
	return autoConvert_v1alpha1_Options_To_openebsio_Options(in, out, s)
}

func autoConvert_openebsio_Options_To_v1alpha1_Options(in *openebsio.Options, out *v1alpha1.Options, s conversion.Scope) error {
	out.Timeout = in.Timeout
	return nil
}

// Convert_openebsio_Options_To_v1alpha1_Options is an autogenerated conversion function.
func Convert_openebsio_Options_To_v1alpha1_Options(in *openebsio.Options, out *v1alpha1.Options, s conversion.Scope) error {
	return autoConvert_openebsio_Options_To_v1alpha1_Options(in, out, s)
}

func autoConvert_v1alpha1_ResourceOptions_To_openebsio_ResourceOptions(in *v1alpha1.ResourceOptions, out *openebsio.ResourceOptions, s conversion.Scope) error {
	out.IgnoreStepsOnError = *(*[]string)(unsafe.Pointer(&in.IgnoreStepsOnError))
	return nil
}

// Convert_v1alpha1_ResourceOptions_To_openebsio_ResourceOptions is an autogenerated conversion function.
func Convert_v1alpha1_ResourceOptions_To_openebsio_ResourceOptions(in *v1alpha1.ResourceOptions, out *openebsio.ResourceOptions, s conversion.Scope) error {
	return autoConvert_v1alpha1_ResourceOptions_To_openebsio_ResourceOptions(in, out, s)
}

func autoConvert_openebsio_ResourceOptions_To_v1alpha1_ResourceOptions(in *openebsio.ResourceOptions, out *v1alpha1.ResourceOptions, s conversion.Scope) error {
	out.IgnoreStepsOnError = *(*[]string)(unsafe.Pointer(&in.IgnoreStepsOnError))
	return nil
}

// Convert_openebsio_ResourceOptions_To_v1alpha1_ResourceOptions is an autogenerated conversion function.
func Convert_openebsio_ResourceOptions_To_v1alpha1_ResourceOptions(in *openebsio.ResourceOptions, out *v1alpha1.ResourceOptions, s conversion.Scope) error {
	return autoConvert_openebsio_ResourceOptions_To_v1alpha1_ResourceOptions(in, out, s)
}

func autoConvert_v1alpha1_ResourceSpec_To_openebsio_ResourceSpec(in *v1alpha1.ResourceSpec, out *openebsio.ResourceSpec, s conversion.Scope) error {
	out.JivaVolume = (*openebsio.JivaVolume)(unsafe.Pointer(in.JivaVolume))
	out.CStorVolume = (*openebsio.CStorVolume)(unsafe.Pointer(in.CStorVolume))
	out.CStorPool = (*openebsio.CStorPool)(unsafe.Pointer(in.CStorPool))
	out.StoragePoolClaim = (*openebsio.StoragePoolClaim)(unsafe.Pointer(in.StoragePoolClaim))
	out.CStorPoolInstance = (*openebsio.CStorPoolInstance)(unsafe.Pointer(in.CStorPoolInstance))
	out.CStorPoolCluster = (*openebsio.CStorPoolCluster)(unsafe.Pointer(in.CStorPoolCluster))
	return nil
}

// Convert_v1alpha1_ResourceSpec_To_openebsio_ResourceSpec is an autogenerated conversion function.
func Convert_v1alpha1_ResourceSpec_To_openebsio_ResourceSpec(in *v1alpha1.ResourceSpec, out *openebsio.ResourceSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ResourceSpec_To_openebsio_ResourceSpec(in, out, s)
}

func autoConvert_openebsio_ResourceSpec_To_v1alpha1_ResourceSpec(in *openebsio.ResourceSpec, out *v1alpha1.ResourceSpec, s conversion.Scope) error {
	out.JivaVolume = (*v1alpha1.JivaVolume)(unsafe.Pointer(in.JivaVolume))
	out.CStorVolume = (*v1alpha1.CStorVolume)(unsafe.Pointer(in.CStorVolume))
	out.CStorPool = (*v1alpha1.CStorPool)(unsafe.Pointer(in.CStorPool))
	out.StoragePoolClaim = (*v1alpha1.StoragePoolClaim)(unsafe.Pointer(in.StoragePoolClaim))
	out.CStorPoolInstance = (*v1alpha1.CStorPoolInstance)(unsafe.Pointer(in.CStorPoolInstance))
	out.CStorPoolCluster = (*v1alpha1.CStorPoolCluster)(unsafe.Pointer(in.CStorPoolCluster))
	return nil
}

// Convert_openebsio_ResourceSpec_To_v1alpha1_ResourceSpec is an autogenerated conversion function.
func Convert_openebsio_ResourceSpec_To_v1alpha1_ResourceSpec(in *openebsio.ResourceSpec, out *v1alpha1.ResourceSpec, s conversion.Scope) error {
	return autoConvert_openebsio_ResourceSpec_To_v1alpha1_ResourceSpec(in, out, s)
}

func autoConvert_v1alpha1_Status_To_openebsio_Status(in *v1alpha1.Status, out *openebsio.Status, s conversion.Scope) error {
	out.Phase = openebsio.StepPhase(in.Phase)
	out.Message = in.Message
	out.Reason = in.Reason
	return nil
}

// Convert_v1alpha1_Status_To_openebsio_Status is an autogenerated conversion function.
func Convert_v1alpha1_Status_To_openebsio_Status(in *v1alpha1.Status, out *openebsio.Status, s conversion.Scope) error {
	return autoConvert_v1alpha1_Status_To_openebsio_Status(in, out, s)
}

func autoConvert_openebsio_Status_To_v1alpha1_Status(in *openebsio.Status, out *v1alpha1.Status, s conversion.Scope) error {
	out.Phase = v1alpha1.StepPhase(in.Phase)
	out.Message = in.Message
	out.Reason = in.Reason
	return nil
}

// Convert_openebsio_Status_To_v1alpha1_Status is an autogenerated conversion function.
func Convert_openebsio_Status_To_v1alpha1_Status(in *openebsio.Status, out *v1alpha1.Status, s conversion.Scope) error {
	return autoConvert_openebsio_Status_To_v1alpha1_Status(in, out, s)
}

func autoConvert_v1alpha1_StoragePoolClaim_To_openebsio_StoragePoolClaim(in *v1alpha1.StoragePoolClaim, out *openebsio.StoragePoolClaim, s conversion.Scope) error {
	out.SPCName = in.SPCName
	out.Options = (*openebsio.ResourceOptions)(unsafe.Pointer(in.Options))
	return nil
}

// Convert_v1alpha1_StoragePoolClaim_To_openebsio_StoragePoolClaim is an autogenerated conversion function.
func Convert_v1alpha1_StoragePoolClaim_To_openebsio_StoragePoolClaim(in *v1alpha1.StoragePoolClaim, out *openebsio.StoragePoolClaim, s conversion.Scope) error {
	return autoConvert_v1alpha1_StoragePoolClaim_To_openebsio_StoragePoolClaim(in, out, s)
}

func autoConvert_openebsio_StoragePoolClaim_To_v1alpha1_StoragePoolClaim(in *openebsio.StoragePoolClaim, out *v1alpha1.StoragePoolClaim, s conversion.Scope) error {
	out.SPCName = in.SPCName
	out.Options = (*v1alpha1.ResourceOptions)(unsafe.Pointer(in.Options))
	return nil
}

// Convert_openebsio_StoragePoolClaim_To_v1alpha1_StoragePoolClaim is an autogenerated conversion function.
func Convert_openebsio_StoragePoolClaim_To_v1alpha1_StoragePoolClaim(in *openebsio.StoragePoolClaim, out *v1alpha1.StoragePoolClaim, s conversion.Scope) error {
	return autoConvert_openebsio_StoragePoolClaim_To_v1alpha1_StoragePoolClaim(in, out, s)
}

func autoConvert_v1alpha1_UpgradeDetailedStatuses_To_openebsio_UpgradeDetailedStatuses(in *v1alpha1.UpgradeDetailedStatuses, out *openebsio.UpgradeDetailedStatuses, s conversion.Scope) error {
	out.Step = openebsio.UpgradeStep(in.Step)
	out.StartTime = in.StartTime
	out.LastUpdatedTime = in.LastUpdatedTime
	if err := Convert_v1alpha1_Status_To_openebsio_Status(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_UpgradeDetailedStatuses_To_openebsio_UpgradeDetailedStatuses is an autogenerated conversion function.
func Convert_v1alpha1_UpgradeDetailedStatuses_To_openebsio_UpgradeDetailedStatuses(in *v1alpha1.UpgradeDetailedStatuses, out *openebsio.UpgradeDetailedStatuses, s conversion.Scope) error {
	return autoConvert_v1alpha1_UpgradeDetailedStatuses_To_openebsio_UpgradeDetailedStatuses(in, out, s)
}

func autoConvert_openebsio_UpgradeDetailedStatuses_To_v1alpha1_UpgradeDetailedStatuses(in *openebsio.UpgradeDetailedStatuses, out *v1alpha1.UpgradeDetailedStatuses, s conversion.Scope) error {
	out.Step = v1alpha1.UpgradeStep(in.Step)
	out.StartTime = in.StartTime
	out.LastUpdatedTime = in.LastUpdatedTime
	if err := Convert_openebsio_Status_To_v1alpha1_Status(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_openebsio_UpgradeDetailedStatuses_To_v1alpha1_UpgradeDetailedStatuses is an autogenerated conversion function.
func Convert_openebsio_UpgradeDetailedStatuses_To_v1alpha1_UpgradeDetailedStatuses(in *openebsio.UpgradeDetailedStatuses, out *v1alpha1.UpgradeDetailedStatuses, s conversion.Scope) error {
	return autoConvert_openebsio_UpgradeDetailedStatuses_To_v1alpha1_UpgradeDetailedStatuses(in, out, s)
}

func autoConvert_v1alpha1_UpgradeTask_To_openebsio_UpgradeTask(in *v1alpha1.UpgradeTask, out *openebsio.UpgradeTask, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_UpgradeTaskSpec_To_openebsio_UpgradeTaskSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_UpgradeTaskStatus_To_openebsio_UpgradeTaskStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_UpgradeTask_To_openebsio_UpgradeTask is an autogenerated conversion function.
func Convert_v1alpha1_UpgradeTask_To_openebsio_UpgradeTask(in *v1alpha1.UpgradeTask, out *openebsio.UpgradeTask, s conversion.Scope) error {
	return autoConvert_v1alpha1_UpgradeTask_To_openebsio_UpgradeTask(in, out, s)
}

func autoConvert_openebsio_UpgradeTask_To_v1alpha1_UpgradeTask(in *openebsio.UpgradeTask, out *v1alpha1.UpgradeTask, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_openebsio_UpgradeTaskSpec_To_v1alpha1_UpgradeTaskSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_openebsio_UpgradeTaskStatus_To_v1alpha1_UpgradeTaskStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_openebsio_UpgradeTask_To_v1alpha1_UpgradeTask is an autogenerated conversion function.
func Convert_openebsio_UpgradeTask_To_v1alpha1_UpgradeTask(in *openebsio.UpgradeTask, out *v1alpha1.UpgradeTask, s conversion.Scope) error {
	return autoConvert_openebsio_UpgradeTask_To_v1alpha1_UpgradeTask(in, out, s)
}

func autoConvert_v1alpha1_UpgradeTaskList_To_openebsio_UpgradeTaskList(in *v1alpha1.UpgradeTaskList, out *openebsio.UpgradeTaskList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]openebsio.UpgradeTask)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_UpgradeTaskList_To_openebsio_UpgradeTaskList is an autogenerated conversion function.
func Convert_v1alpha1_UpgradeTaskList_To_openebsio_UpgradeTaskList(in *v1alpha1.UpgradeTaskList, out *openebsio.UpgradeTaskList, s conversion.Scope) error {
	return autoConvert_v1alpha1_UpgradeTaskList_To_openebsio_UpgradeTaskList(in, out, s)
}

func autoConvert_openebsio_UpgradeTaskList_To_v1alpha1_UpgradeTaskList(in *openebsio.UpgradeTaskList, out *v1alpha1.UpgradeTaskList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1alpha1.UpgradeTask)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_openebsio_UpgradeTaskList_To_v1alpha1_UpgradeTaskList is an autogenerated conversion function.
func Convert_openebsio_UpgradeTaskList_To_v1alpha1_UpgradeTaskList(in *openebsio.UpgradeTaskList, out *v1alpha1.UpgradeTaskList, s conversion.Scope) error {
	return autoConvert_openebsio_UpgradeTaskList_To_v1alpha1_UpgradeTaskList(in, out, s)
}

func autoConvert_v1alpha1_UpgradeTaskSpec_To_openebsio_UpgradeTaskSpec(in *v1alpha1.UpgradeTaskSpec, out *openebsio.UpgradeTaskSpec, s conversion.Scope) error {
	out.FromVersion = in.FromVersion
	out.ToVersion = in.ToVersion
	out.Options = (*openebsio.Options)(unsafe.Pointer(in.Options))
	if err := Convert_v1alpha1_ResourceSpec_To_openebsio_ResourceSpec(&in.ResourceSpec, &out.ResourceSpec, s); err != nil {
		return err
	}
	out.ImagePrefix = in.ImagePrefix
	out.ImageTag = in.ImageTag
	return nil
}

// Convert_v1alpha1_UpgradeTaskSpec_To_openebsio_UpgradeTaskSpec is an autogenerated conversion function.
func Convert_v1alpha1_UpgradeTaskSpec_To_openebsio_UpgradeTaskSpec(in *v1alpha1.UpgradeTaskSpec, out *openebsio.UpgradeTaskSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_UpgradeTaskSpec_To_openebsio_UpgradeTaskSpec(in, out, s)
}

func autoConvert_openebsio_UpgradeTaskSpec_To_v1alpha1_UpgradeTaskSpec(in *openebsio.UpgradeTaskSpec, out *v1alpha1.UpgradeTaskSpec, s conversion.Scope) error {
	out.FromVersion = in.FromVersion
	out.ToVersion = in.ToVersion
	out.Options = (*v1alpha1.Options)(unsafe.Pointer(in.Options))
	if err := Convert_openebsio_ResourceSpec_To_v1alpha1_ResourceSpec(&in.ResourceSpec, &out.ResourceSpec, s); err != nil {
		return err
	}
	out.ImagePrefix = in.ImagePrefix
	out.ImageTag = in.ImageTag
	return nil
}

// Convert_openebsio_UpgradeTaskSpec_To_v1alpha1_UpgradeTaskSpec is an autogenerated conversion function.
func Convert_openebsio_UpgradeTaskSpec_To_v1alpha1_UpgradeTaskSpec(in *openebsio.UpgradeTaskSpec, out *v1alpha1.UpgradeTaskSpec, s conversion.Scope) error {
	return autoConvert_openebsio_UpgradeTaskSpec_To_v1alpha1_UpgradeTaskSpec(in, out, s)
}

func autoConvert_v1alpha1_UpgradeTaskStatus_To_openebsio_UpgradeTaskStatus(in *v1alpha1.UpgradeTaskStatus, out *openebsio.UpgradeTaskStatus, s conversion.Scope) error {
	out.Phase = openebsio.UpgradePhase(in.Phase)
	out.StartTime = in.StartTime
	out.CompletedTime = in.CompletedTime
	out.UpgradeDetailedStatuses = *(*[]openebsio.UpgradeDetailedStatuses)(unsafe.Pointer(&in.UpgradeDetailedStatuses))
	out.Retries = in.Retries
	return nil
}

// Convert_v1alpha1_UpgradeTaskStatus_To_openebsio_UpgradeTaskStatus is an autogenerated conversion function.
func Convert_v1alpha1_UpgradeTaskStatus_To_openebsio_UpgradeTaskStatus(in *v1alpha1.UpgradeTaskStatus, out *openebsio.UpgradeTaskStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_UpgradeTaskStatus_To_openebsio_UpgradeTaskStatus(in, out, s)
}

func autoConvert_openebsio_UpgradeTaskStatus_To_v1alpha1_UpgradeTaskStatus(in *openebsio.UpgradeTaskStatus, out *v1alpha1.UpgradeTaskStatus, s conversion.Scope) error {
	out.Phase = v1alpha1.UpgradePhase(in.Phase)
	out.StartTime = in.StartTime
	out.CompletedTime = in.CompletedTime
	out.UpgradeDetailedStatuses = *(*[]v1alpha1.UpgradeDetailedStatuses)(unsafe.Pointer(&in.UpgradeDetailedStatuses))
	out.Retries = in.Retries
	return nil
}

// Convert_openebsio_UpgradeTaskStatus_To_v1alpha1_UpgradeTaskStatus is an autogenerated conversion function.
func Convert_openebsio_UpgradeTaskStatus_To_v1alpha1_UpgradeTaskStatus(in *openebsio.UpgradeTaskStatus, out *v1alpha1.UpgradeTaskStatus, s conversion.Scope) error {
	return autoConvert_openebsio_UpgradeTaskStatus_To_v1alpha1_UpgradeTaskStatus(in, out, s)
}
