// +build !ignore_autogenerated

/*
Copyright 2020 The OpenEBS Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1

import (
	unsafe "unsafe"

	v1 "github.com/openebs/api/pkg/apis/cstor/v1"
	cstor "github.com/openebs/api/pkg/internalapis/apis/cstor"
	corev1 "k8s.io/api/core/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*v1.CStorPoolCluster)(nil), (*cstor.CStorPoolCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_CStorPoolCluster_To_cstor_CStorPoolCluster(a.(*v1.CStorPoolCluster), b.(*cstor.CStorPoolCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cstor.CStorPoolCluster)(nil), (*v1.CStorPoolCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cstor_CStorPoolCluster_To_v1_CStorPoolCluster(a.(*cstor.CStorPoolCluster), b.(*v1.CStorPoolCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.CStorPoolClusterBlockDevice)(nil), (*cstor.CStorPoolClusterBlockDevice)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_CStorPoolClusterBlockDevice_To_cstor_CStorPoolClusterBlockDevice(a.(*v1.CStorPoolClusterBlockDevice), b.(*cstor.CStorPoolClusterBlockDevice), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cstor.CStorPoolClusterBlockDevice)(nil), (*v1.CStorPoolClusterBlockDevice)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cstor_CStorPoolClusterBlockDevice_To_v1_CStorPoolClusterBlockDevice(a.(*cstor.CStorPoolClusterBlockDevice), b.(*v1.CStorPoolClusterBlockDevice), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.CStorPoolClusterCondition)(nil), (*cstor.CStorPoolClusterCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_CStorPoolClusterCondition_To_cstor_CStorPoolClusterCondition(a.(*v1.CStorPoolClusterCondition), b.(*cstor.CStorPoolClusterCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cstor.CStorPoolClusterCondition)(nil), (*v1.CStorPoolClusterCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cstor_CStorPoolClusterCondition_To_v1_CStorPoolClusterCondition(a.(*cstor.CStorPoolClusterCondition), b.(*v1.CStorPoolClusterCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.CStorPoolClusterList)(nil), (*cstor.CStorPoolClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_CStorPoolClusterList_To_cstor_CStorPoolClusterList(a.(*v1.CStorPoolClusterList), b.(*cstor.CStorPoolClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cstor.CStorPoolClusterList)(nil), (*v1.CStorPoolClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cstor_CStorPoolClusterList_To_v1_CStorPoolClusterList(a.(*cstor.CStorPoolClusterList), b.(*v1.CStorPoolClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.CStorPoolClusterSpec)(nil), (*cstor.CStorPoolClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_CStorPoolClusterSpec_To_cstor_CStorPoolClusterSpec(a.(*v1.CStorPoolClusterSpec), b.(*cstor.CStorPoolClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cstor.CStorPoolClusterSpec)(nil), (*v1.CStorPoolClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cstor_CStorPoolClusterSpec_To_v1_CStorPoolClusterSpec(a.(*cstor.CStorPoolClusterSpec), b.(*v1.CStorPoolClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.CStorPoolClusterStatus)(nil), (*cstor.CStorPoolClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_CStorPoolClusterStatus_To_cstor_CStorPoolClusterStatus(a.(*v1.CStorPoolClusterStatus), b.(*cstor.CStorPoolClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cstor.CStorPoolClusterStatus)(nil), (*v1.CStorPoolClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cstor_CStorPoolClusterStatus_To_v1_CStorPoolClusterStatus(a.(*cstor.CStorPoolClusterStatus), b.(*v1.CStorPoolClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.CStorPoolInstacneCapacity)(nil), (*cstor.CStorPoolInstacneCapacity)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_CStorPoolInstacneCapacity_To_cstor_CStorPoolInstacneCapacity(a.(*v1.CStorPoolInstacneCapacity), b.(*cstor.CStorPoolInstacneCapacity), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cstor.CStorPoolInstacneCapacity)(nil), (*v1.CStorPoolInstacneCapacity)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cstor_CStorPoolInstacneCapacity_To_v1_CStorPoolInstacneCapacity(a.(*cstor.CStorPoolInstacneCapacity), b.(*v1.CStorPoolInstacneCapacity), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.CStorPoolInstance)(nil), (*cstor.CStorPoolInstance)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_CStorPoolInstance_To_cstor_CStorPoolInstance(a.(*v1.CStorPoolInstance), b.(*cstor.CStorPoolInstance), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cstor.CStorPoolInstance)(nil), (*v1.CStorPoolInstance)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cstor_CStorPoolInstance_To_v1_CStorPoolInstance(a.(*cstor.CStorPoolInstance), b.(*v1.CStorPoolInstance), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.CStorPoolInstanceCondition)(nil), (*cstor.CStorPoolInstanceCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_CStorPoolInstanceCondition_To_cstor_CStorPoolInstanceCondition(a.(*v1.CStorPoolInstanceCondition), b.(*cstor.CStorPoolInstanceCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cstor.CStorPoolInstanceCondition)(nil), (*v1.CStorPoolInstanceCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cstor_CStorPoolInstanceCondition_To_v1_CStorPoolInstanceCondition(a.(*cstor.CStorPoolInstanceCondition), b.(*v1.CStorPoolInstanceCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.CStorPoolInstanceList)(nil), (*cstor.CStorPoolInstanceList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_CStorPoolInstanceList_To_cstor_CStorPoolInstanceList(a.(*v1.CStorPoolInstanceList), b.(*cstor.CStorPoolInstanceList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cstor.CStorPoolInstanceList)(nil), (*v1.CStorPoolInstanceList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cstor_CStorPoolInstanceList_To_v1_CStorPoolInstanceList(a.(*cstor.CStorPoolInstanceList), b.(*v1.CStorPoolInstanceList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.CStorPoolInstanceSpec)(nil), (*cstor.CStorPoolInstanceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_CStorPoolInstanceSpec_To_cstor_CStorPoolInstanceSpec(a.(*v1.CStorPoolInstanceSpec), b.(*cstor.CStorPoolInstanceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cstor.CStorPoolInstanceSpec)(nil), (*v1.CStorPoolInstanceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cstor_CStorPoolInstanceSpec_To_v1_CStorPoolInstanceSpec(a.(*cstor.CStorPoolInstanceSpec), b.(*v1.CStorPoolInstanceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.CStorPoolInstanceStatus)(nil), (*cstor.CStorPoolInstanceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_CStorPoolInstanceStatus_To_cstor_CStorPoolInstanceStatus(a.(*v1.CStorPoolInstanceStatus), b.(*cstor.CStorPoolInstanceStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cstor.CStorPoolInstanceStatus)(nil), (*v1.CStorPoolInstanceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cstor_CStorPoolInstanceStatus_To_v1_CStorPoolInstanceStatus(a.(*cstor.CStorPoolInstanceStatus), b.(*v1.CStorPoolInstanceStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.PoolConfig)(nil), (*cstor.PoolConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_PoolConfig_To_cstor_PoolConfig(a.(*v1.PoolConfig), b.(*cstor.PoolConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cstor.PoolConfig)(nil), (*v1.PoolConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cstor_PoolConfig_To_v1_PoolConfig(a.(*cstor.PoolConfig), b.(*v1.PoolConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.PoolSpec)(nil), (*cstor.PoolSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_PoolSpec_To_cstor_PoolSpec(a.(*v1.PoolSpec), b.(*cstor.PoolSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cstor.PoolSpec)(nil), (*v1.PoolSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cstor_PoolSpec_To_v1_PoolSpec(a.(*cstor.PoolSpec), b.(*v1.PoolSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.RaidGroup)(nil), (*cstor.RaidGroup)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_RaidGroup_To_cstor_RaidGroup(a.(*v1.RaidGroup), b.(*cstor.RaidGroup), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cstor.RaidGroup)(nil), (*v1.RaidGroup)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cstor_RaidGroup_To_v1_RaidGroup(a.(*cstor.RaidGroup), b.(*v1.RaidGroup), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.VersionDetails)(nil), (*cstor.VersionDetails)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_VersionDetails_To_cstor_VersionDetails(a.(*v1.VersionDetails), b.(*cstor.VersionDetails), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cstor.VersionDetails)(nil), (*v1.VersionDetails)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cstor_VersionDetails_To_v1_VersionDetails(a.(*cstor.VersionDetails), b.(*v1.VersionDetails), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.VersionStatus)(nil), (*cstor.VersionStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_VersionStatus_To_cstor_VersionStatus(a.(*v1.VersionStatus), b.(*cstor.VersionStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cstor.VersionStatus)(nil), (*v1.VersionStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cstor_VersionStatus_To_v1_VersionStatus(a.(*cstor.VersionStatus), b.(*v1.VersionStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1_CStorPoolCluster_To_cstor_CStorPoolCluster(in *v1.CStorPoolCluster, out *cstor.CStorPoolCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_CStorPoolClusterSpec_To_cstor_CStorPoolClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1_CStorPoolClusterStatus_To_cstor_CStorPoolClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	if err := Convert_v1_VersionDetails_To_cstor_VersionDetails(&in.VersionDetails, &out.VersionDetails, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_CStorPoolCluster_To_cstor_CStorPoolCluster is an autogenerated conversion function.
func Convert_v1_CStorPoolCluster_To_cstor_CStorPoolCluster(in *v1.CStorPoolCluster, out *cstor.CStorPoolCluster, s conversion.Scope) error {
	return autoConvert_v1_CStorPoolCluster_To_cstor_CStorPoolCluster(in, out, s)
}

func autoConvert_cstor_CStorPoolCluster_To_v1_CStorPoolCluster(in *cstor.CStorPoolCluster, out *v1.CStorPoolCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_cstor_CStorPoolClusterSpec_To_v1_CStorPoolClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_cstor_CStorPoolClusterStatus_To_v1_CStorPoolClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	if err := Convert_cstor_VersionDetails_To_v1_VersionDetails(&in.VersionDetails, &out.VersionDetails, s); err != nil {
		return err
	}
	return nil
}

// Convert_cstor_CStorPoolCluster_To_v1_CStorPoolCluster is an autogenerated conversion function.
func Convert_cstor_CStorPoolCluster_To_v1_CStorPoolCluster(in *cstor.CStorPoolCluster, out *v1.CStorPoolCluster, s conversion.Scope) error {
	return autoConvert_cstor_CStorPoolCluster_To_v1_CStorPoolCluster(in, out, s)
}

func autoConvert_v1_CStorPoolClusterBlockDevice_To_cstor_CStorPoolClusterBlockDevice(in *v1.CStorPoolClusterBlockDevice, out *cstor.CStorPoolClusterBlockDevice, s conversion.Scope) error {
	out.BlockDeviceName = in.BlockDeviceName
	out.Capacity = in.Capacity
	out.DevLink = in.DevLink
	return nil
}

// Convert_v1_CStorPoolClusterBlockDevice_To_cstor_CStorPoolClusterBlockDevice is an autogenerated conversion function.
func Convert_v1_CStorPoolClusterBlockDevice_To_cstor_CStorPoolClusterBlockDevice(in *v1.CStorPoolClusterBlockDevice, out *cstor.CStorPoolClusterBlockDevice, s conversion.Scope) error {
	return autoConvert_v1_CStorPoolClusterBlockDevice_To_cstor_CStorPoolClusterBlockDevice(in, out, s)
}

func autoConvert_cstor_CStorPoolClusterBlockDevice_To_v1_CStorPoolClusterBlockDevice(in *cstor.CStorPoolClusterBlockDevice, out *v1.CStorPoolClusterBlockDevice, s conversion.Scope) error {
	out.BlockDeviceName = in.BlockDeviceName
	out.Capacity = in.Capacity
	out.DevLink = in.DevLink
	return nil
}

// Convert_cstor_CStorPoolClusterBlockDevice_To_v1_CStorPoolClusterBlockDevice is an autogenerated conversion function.
func Convert_cstor_CStorPoolClusterBlockDevice_To_v1_CStorPoolClusterBlockDevice(in *cstor.CStorPoolClusterBlockDevice, out *v1.CStorPoolClusterBlockDevice, s conversion.Scope) error {
	return autoConvert_cstor_CStorPoolClusterBlockDevice_To_v1_CStorPoolClusterBlockDevice(in, out, s)
}

func autoConvert_v1_CStorPoolClusterCondition_To_cstor_CStorPoolClusterCondition(in *v1.CStorPoolClusterCondition, out *cstor.CStorPoolClusterCondition, s conversion.Scope) error {
	out.Type = cstor.CSPCConditionType(in.Type)
	out.Status = corev1.ConditionStatus(in.Status)
	out.LastUpdateTime = in.LastUpdateTime
	out.LastTransitionTime = in.LastTransitionTime
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

// Convert_v1_CStorPoolClusterCondition_To_cstor_CStorPoolClusterCondition is an autogenerated conversion function.
func Convert_v1_CStorPoolClusterCondition_To_cstor_CStorPoolClusterCondition(in *v1.CStorPoolClusterCondition, out *cstor.CStorPoolClusterCondition, s conversion.Scope) error {
	return autoConvert_v1_CStorPoolClusterCondition_To_cstor_CStorPoolClusterCondition(in, out, s)
}

func autoConvert_cstor_CStorPoolClusterCondition_To_v1_CStorPoolClusterCondition(in *cstor.CStorPoolClusterCondition, out *v1.CStorPoolClusterCondition, s conversion.Scope) error {
	out.Type = v1.CSPCConditionType(in.Type)
	out.Status = corev1.ConditionStatus(in.Status)
	out.LastUpdateTime = in.LastUpdateTime
	out.LastTransitionTime = in.LastTransitionTime
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

// Convert_cstor_CStorPoolClusterCondition_To_v1_CStorPoolClusterCondition is an autogenerated conversion function.
func Convert_cstor_CStorPoolClusterCondition_To_v1_CStorPoolClusterCondition(in *cstor.CStorPoolClusterCondition, out *v1.CStorPoolClusterCondition, s conversion.Scope) error {
	return autoConvert_cstor_CStorPoolClusterCondition_To_v1_CStorPoolClusterCondition(in, out, s)
}

func autoConvert_v1_CStorPoolClusterList_To_cstor_CStorPoolClusterList(in *v1.CStorPoolClusterList, out *cstor.CStorPoolClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]cstor.CStorPoolCluster)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_CStorPoolClusterList_To_cstor_CStorPoolClusterList is an autogenerated conversion function.
func Convert_v1_CStorPoolClusterList_To_cstor_CStorPoolClusterList(in *v1.CStorPoolClusterList, out *cstor.CStorPoolClusterList, s conversion.Scope) error {
	return autoConvert_v1_CStorPoolClusterList_To_cstor_CStorPoolClusterList(in, out, s)
}

func autoConvert_cstor_CStorPoolClusterList_To_v1_CStorPoolClusterList(in *cstor.CStorPoolClusterList, out *v1.CStorPoolClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1.CStorPoolCluster)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_cstor_CStorPoolClusterList_To_v1_CStorPoolClusterList is an autogenerated conversion function.
func Convert_cstor_CStorPoolClusterList_To_v1_CStorPoolClusterList(in *cstor.CStorPoolClusterList, out *v1.CStorPoolClusterList, s conversion.Scope) error {
	return autoConvert_cstor_CStorPoolClusterList_To_v1_CStorPoolClusterList(in, out, s)
}

func autoConvert_v1_CStorPoolClusterSpec_To_cstor_CStorPoolClusterSpec(in *v1.CStorPoolClusterSpec, out *cstor.CStorPoolClusterSpec, s conversion.Scope) error {
	out.Pools = *(*[]cstor.PoolSpec)(unsafe.Pointer(&in.Pools))
	out.DefaultResources = (*corev1.ResourceRequirements)(unsafe.Pointer(in.DefaultResources))
	out.DefaultAuxResources = (*corev1.ResourceRequirements)(unsafe.Pointer(in.DefaultAuxResources))
	out.Tolerations = *(*[]corev1.Toleration)(unsafe.Pointer(&in.Tolerations))
	out.DefaultPriorityClassName = in.DefaultPriorityClassName
	return nil
}

// Convert_v1_CStorPoolClusterSpec_To_cstor_CStorPoolClusterSpec is an autogenerated conversion function.
func Convert_v1_CStorPoolClusterSpec_To_cstor_CStorPoolClusterSpec(in *v1.CStorPoolClusterSpec, out *cstor.CStorPoolClusterSpec, s conversion.Scope) error {
	return autoConvert_v1_CStorPoolClusterSpec_To_cstor_CStorPoolClusterSpec(in, out, s)
}

func autoConvert_cstor_CStorPoolClusterSpec_To_v1_CStorPoolClusterSpec(in *cstor.CStorPoolClusterSpec, out *v1.CStorPoolClusterSpec, s conversion.Scope) error {
	out.Pools = *(*[]v1.PoolSpec)(unsafe.Pointer(&in.Pools))
	out.DefaultResources = (*corev1.ResourceRequirements)(unsafe.Pointer(in.DefaultResources))
	out.DefaultAuxResources = (*corev1.ResourceRequirements)(unsafe.Pointer(in.DefaultAuxResources))
	out.Tolerations = *(*[]corev1.Toleration)(unsafe.Pointer(&in.Tolerations))
	out.DefaultPriorityClassName = in.DefaultPriorityClassName
	return nil
}

// Convert_cstor_CStorPoolClusterSpec_To_v1_CStorPoolClusterSpec is an autogenerated conversion function.
func Convert_cstor_CStorPoolClusterSpec_To_v1_CStorPoolClusterSpec(in *cstor.CStorPoolClusterSpec, out *v1.CStorPoolClusterSpec, s conversion.Scope) error {
	return autoConvert_cstor_CStorPoolClusterSpec_To_v1_CStorPoolClusterSpec(in, out, s)
}

func autoConvert_v1_CStorPoolClusterStatus_To_cstor_CStorPoolClusterStatus(in *v1.CStorPoolClusterStatus, out *cstor.CStorPoolClusterStatus, s conversion.Scope) error {
	out.CurrentProvisionedInstances = in.CurrentProvisionedInstances
	out.RunningInstances = in.RunningInstances
	out.HealthyInstances = in.HealthyInstances
	out.Conditions = *(*[]cstor.CStorPoolClusterCondition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1_CStorPoolClusterStatus_To_cstor_CStorPoolClusterStatus is an autogenerated conversion function.
func Convert_v1_CStorPoolClusterStatus_To_cstor_CStorPoolClusterStatus(in *v1.CStorPoolClusterStatus, out *cstor.CStorPoolClusterStatus, s conversion.Scope) error {
	return autoConvert_v1_CStorPoolClusterStatus_To_cstor_CStorPoolClusterStatus(in, out, s)
}

func autoConvert_cstor_CStorPoolClusterStatus_To_v1_CStorPoolClusterStatus(in *cstor.CStorPoolClusterStatus, out *v1.CStorPoolClusterStatus, s conversion.Scope) error {
	out.CurrentProvisionedInstances = in.CurrentProvisionedInstances
	out.RunningInstances = in.RunningInstances
	out.HealthyInstances = in.HealthyInstances
	out.Conditions = *(*[]v1.CStorPoolClusterCondition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_cstor_CStorPoolClusterStatus_To_v1_CStorPoolClusterStatus is an autogenerated conversion function.
func Convert_cstor_CStorPoolClusterStatus_To_v1_CStorPoolClusterStatus(in *cstor.CStorPoolClusterStatus, out *v1.CStorPoolClusterStatus, s conversion.Scope) error {
	return autoConvert_cstor_CStorPoolClusterStatus_To_v1_CStorPoolClusterStatus(in, out, s)
}

func autoConvert_v1_CStorPoolInstacneCapacity_To_cstor_CStorPoolInstacneCapacity(in *v1.CStorPoolInstacneCapacity, out *cstor.CStorPoolInstacneCapacity, s conversion.Scope) error {
	out.Total = in.Total
	out.Free = in.Free
	out.Used = in.Used
	return nil
}

// Convert_v1_CStorPoolInstacneCapacity_To_cstor_CStorPoolInstacneCapacity is an autogenerated conversion function.
func Convert_v1_CStorPoolInstacneCapacity_To_cstor_CStorPoolInstacneCapacity(in *v1.CStorPoolInstacneCapacity, out *cstor.CStorPoolInstacneCapacity, s conversion.Scope) error {
	return autoConvert_v1_CStorPoolInstacneCapacity_To_cstor_CStorPoolInstacneCapacity(in, out, s)
}

func autoConvert_cstor_CStorPoolInstacneCapacity_To_v1_CStorPoolInstacneCapacity(in *cstor.CStorPoolInstacneCapacity, out *v1.CStorPoolInstacneCapacity, s conversion.Scope) error {
	out.Total = in.Total
	out.Free = in.Free
	out.Used = in.Used
	return nil
}

// Convert_cstor_CStorPoolInstacneCapacity_To_v1_CStorPoolInstacneCapacity is an autogenerated conversion function.
func Convert_cstor_CStorPoolInstacneCapacity_To_v1_CStorPoolInstacneCapacity(in *cstor.CStorPoolInstacneCapacity, out *v1.CStorPoolInstacneCapacity, s conversion.Scope) error {
	return autoConvert_cstor_CStorPoolInstacneCapacity_To_v1_CStorPoolInstacneCapacity(in, out, s)
}

func autoConvert_v1_CStorPoolInstance_To_cstor_CStorPoolInstance(in *v1.CStorPoolInstance, out *cstor.CStorPoolInstance, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_CStorPoolInstanceSpec_To_cstor_CStorPoolInstanceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1_CStorPoolInstanceStatus_To_cstor_CStorPoolInstanceStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	if err := Convert_v1_VersionDetails_To_cstor_VersionDetails(&in.VersionDetails, &out.VersionDetails, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_CStorPoolInstance_To_cstor_CStorPoolInstance is an autogenerated conversion function.
func Convert_v1_CStorPoolInstance_To_cstor_CStorPoolInstance(in *v1.CStorPoolInstance, out *cstor.CStorPoolInstance, s conversion.Scope) error {
	return autoConvert_v1_CStorPoolInstance_To_cstor_CStorPoolInstance(in, out, s)
}

func autoConvert_cstor_CStorPoolInstance_To_v1_CStorPoolInstance(in *cstor.CStorPoolInstance, out *v1.CStorPoolInstance, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_cstor_CStorPoolInstanceSpec_To_v1_CStorPoolInstanceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_cstor_CStorPoolInstanceStatus_To_v1_CStorPoolInstanceStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	if err := Convert_cstor_VersionDetails_To_v1_VersionDetails(&in.VersionDetails, &out.VersionDetails, s); err != nil {
		return err
	}
	return nil
}

// Convert_cstor_CStorPoolInstance_To_v1_CStorPoolInstance is an autogenerated conversion function.
func Convert_cstor_CStorPoolInstance_To_v1_CStorPoolInstance(in *cstor.CStorPoolInstance, out *v1.CStorPoolInstance, s conversion.Scope) error {
	return autoConvert_cstor_CStorPoolInstance_To_v1_CStorPoolInstance(in, out, s)
}

func autoConvert_v1_CStorPoolInstanceCondition_To_cstor_CStorPoolInstanceCondition(in *v1.CStorPoolInstanceCondition, out *cstor.CStorPoolInstanceCondition, s conversion.Scope) error {
	out.Type = cstor.CSPIConditionType(in.Type)
	out.Status = corev1.ConditionStatus(in.Status)
	out.LastUpdateTime = in.LastUpdateTime
	out.LastTransitionTime = in.LastTransitionTime
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

// Convert_v1_CStorPoolInstanceCondition_To_cstor_CStorPoolInstanceCondition is an autogenerated conversion function.
func Convert_v1_CStorPoolInstanceCondition_To_cstor_CStorPoolInstanceCondition(in *v1.CStorPoolInstanceCondition, out *cstor.CStorPoolInstanceCondition, s conversion.Scope) error {
	return autoConvert_v1_CStorPoolInstanceCondition_To_cstor_CStorPoolInstanceCondition(in, out, s)
}

func autoConvert_cstor_CStorPoolInstanceCondition_To_v1_CStorPoolInstanceCondition(in *cstor.CStorPoolInstanceCondition, out *v1.CStorPoolInstanceCondition, s conversion.Scope) error {
	out.Type = v1.CSPIConditionType(in.Type)
	out.Status = corev1.ConditionStatus(in.Status)
	out.LastUpdateTime = in.LastUpdateTime
	out.LastTransitionTime = in.LastTransitionTime
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

// Convert_cstor_CStorPoolInstanceCondition_To_v1_CStorPoolInstanceCondition is an autogenerated conversion function.
func Convert_cstor_CStorPoolInstanceCondition_To_v1_CStorPoolInstanceCondition(in *cstor.CStorPoolInstanceCondition, out *v1.CStorPoolInstanceCondition, s conversion.Scope) error {
	return autoConvert_cstor_CStorPoolInstanceCondition_To_v1_CStorPoolInstanceCondition(in, out, s)
}

func autoConvert_v1_CStorPoolInstanceList_To_cstor_CStorPoolInstanceList(in *v1.CStorPoolInstanceList, out *cstor.CStorPoolInstanceList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]cstor.CStorPoolInstance)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_CStorPoolInstanceList_To_cstor_CStorPoolInstanceList is an autogenerated conversion function.
func Convert_v1_CStorPoolInstanceList_To_cstor_CStorPoolInstanceList(in *v1.CStorPoolInstanceList, out *cstor.CStorPoolInstanceList, s conversion.Scope) error {
	return autoConvert_v1_CStorPoolInstanceList_To_cstor_CStorPoolInstanceList(in, out, s)
}

func autoConvert_cstor_CStorPoolInstanceList_To_v1_CStorPoolInstanceList(in *cstor.CStorPoolInstanceList, out *v1.CStorPoolInstanceList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1.CStorPoolInstance)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_cstor_CStorPoolInstanceList_To_v1_CStorPoolInstanceList is an autogenerated conversion function.
func Convert_cstor_CStorPoolInstanceList_To_v1_CStorPoolInstanceList(in *cstor.CStorPoolInstanceList, out *v1.CStorPoolInstanceList, s conversion.Scope) error {
	return autoConvert_cstor_CStorPoolInstanceList_To_v1_CStorPoolInstanceList(in, out, s)
}

func autoConvert_v1_CStorPoolInstanceSpec_To_cstor_CStorPoolInstanceSpec(in *v1.CStorPoolInstanceSpec, out *cstor.CStorPoolInstanceSpec, s conversion.Scope) error {
	out.HostName = in.HostName
	out.NodeSelector = *(*map[string]string)(unsafe.Pointer(&in.NodeSelector))
	if err := Convert_v1_PoolConfig_To_cstor_PoolConfig(&in.PoolConfig, &out.PoolConfig, s); err != nil {
		return err
	}
	out.RaidGroups = *(*[]cstor.RaidGroup)(unsafe.Pointer(&in.RaidGroups))
	return nil
}

// Convert_v1_CStorPoolInstanceSpec_To_cstor_CStorPoolInstanceSpec is an autogenerated conversion function.
func Convert_v1_CStorPoolInstanceSpec_To_cstor_CStorPoolInstanceSpec(in *v1.CStorPoolInstanceSpec, out *cstor.CStorPoolInstanceSpec, s conversion.Scope) error {
	return autoConvert_v1_CStorPoolInstanceSpec_To_cstor_CStorPoolInstanceSpec(in, out, s)
}

func autoConvert_cstor_CStorPoolInstanceSpec_To_v1_CStorPoolInstanceSpec(in *cstor.CStorPoolInstanceSpec, out *v1.CStorPoolInstanceSpec, s conversion.Scope) error {
	out.HostName = in.HostName
	out.NodeSelector = *(*map[string]string)(unsafe.Pointer(&in.NodeSelector))
	if err := Convert_cstor_PoolConfig_To_v1_PoolConfig(&in.PoolConfig, &out.PoolConfig, s); err != nil {
		return err
	}
	out.RaidGroups = *(*[]v1.RaidGroup)(unsafe.Pointer(&in.RaidGroups))
	return nil
}

// Convert_cstor_CStorPoolInstanceSpec_To_v1_CStorPoolInstanceSpec is an autogenerated conversion function.
func Convert_cstor_CStorPoolInstanceSpec_To_v1_CStorPoolInstanceSpec(in *cstor.CStorPoolInstanceSpec, out *v1.CStorPoolInstanceSpec, s conversion.Scope) error {
	return autoConvert_cstor_CStorPoolInstanceSpec_To_v1_CStorPoolInstanceSpec(in, out, s)
}

func autoConvert_v1_CStorPoolInstanceStatus_To_cstor_CStorPoolInstanceStatus(in *v1.CStorPoolInstanceStatus, out *cstor.CStorPoolInstanceStatus, s conversion.Scope) error {
	out.Conditions = *(*[]cstor.CStorPoolInstanceCondition)(unsafe.Pointer(&in.Conditions))
	out.Phase = cstor.CStorPoolInstancePhase(in.Phase)
	if err := Convert_v1_CStorPoolInstacneCapacity_To_cstor_CStorPoolInstacneCapacity(&in.Capacity, &out.Capacity, s); err != nil {
		return err
	}
	out.LastTransitionTime = in.LastTransitionTime
	out.LastUpdateTime = in.LastUpdateTime
	out.Message = in.Message
	return nil
}

// Convert_v1_CStorPoolInstanceStatus_To_cstor_CStorPoolInstanceStatus is an autogenerated conversion function.
func Convert_v1_CStorPoolInstanceStatus_To_cstor_CStorPoolInstanceStatus(in *v1.CStorPoolInstanceStatus, out *cstor.CStorPoolInstanceStatus, s conversion.Scope) error {
	return autoConvert_v1_CStorPoolInstanceStatus_To_cstor_CStorPoolInstanceStatus(in, out, s)
}

func autoConvert_cstor_CStorPoolInstanceStatus_To_v1_CStorPoolInstanceStatus(in *cstor.CStorPoolInstanceStatus, out *v1.CStorPoolInstanceStatus, s conversion.Scope) error {
	out.Conditions = *(*[]v1.CStorPoolInstanceCondition)(unsafe.Pointer(&in.Conditions))
	out.Phase = v1.CStorPoolInstancePhase(in.Phase)
	if err := Convert_cstor_CStorPoolInstacneCapacity_To_v1_CStorPoolInstacneCapacity(&in.Capacity, &out.Capacity, s); err != nil {
		return err
	}
	out.LastTransitionTime = in.LastTransitionTime
	out.LastUpdateTime = in.LastUpdateTime
	out.Message = in.Message
	return nil
}

// Convert_cstor_CStorPoolInstanceStatus_To_v1_CStorPoolInstanceStatus is an autogenerated conversion function.
func Convert_cstor_CStorPoolInstanceStatus_To_v1_CStorPoolInstanceStatus(in *cstor.CStorPoolInstanceStatus, out *v1.CStorPoolInstanceStatus, s conversion.Scope) error {
	return autoConvert_cstor_CStorPoolInstanceStatus_To_v1_CStorPoolInstanceStatus(in, out, s)
}

func autoConvert_v1_PoolConfig_To_cstor_PoolConfig(in *v1.PoolConfig, out *cstor.PoolConfig, s conversion.Scope) error {
	out.DataRaidGroupType = in.DataRaidGroupType
	out.WriteCacheGroupType = in.WriteCacheGroupType
	out.ThickProvisioning = in.ThickProvisioning
	out.Compression = in.Compression
	out.Resources = (*corev1.ResourceRequirements)(unsafe.Pointer(in.Resources))
	out.AuxResources = (*corev1.ResourceRequirements)(unsafe.Pointer(in.AuxResources))
	out.Tolerations = *(*[]corev1.Toleration)(unsafe.Pointer(&in.Tolerations))
	out.PriorityClassName = in.PriorityClassName
	return nil
}

// Convert_v1_PoolConfig_To_cstor_PoolConfig is an autogenerated conversion function.
func Convert_v1_PoolConfig_To_cstor_PoolConfig(in *v1.PoolConfig, out *cstor.PoolConfig, s conversion.Scope) error {
	return autoConvert_v1_PoolConfig_To_cstor_PoolConfig(in, out, s)
}

func autoConvert_cstor_PoolConfig_To_v1_PoolConfig(in *cstor.PoolConfig, out *v1.PoolConfig, s conversion.Scope) error {
	out.DataRaidGroupType = in.DataRaidGroupType
	out.WriteCacheGroupType = in.WriteCacheGroupType
	out.ThickProvisioning = in.ThickProvisioning
	out.Compression = in.Compression
	out.Resources = (*corev1.ResourceRequirements)(unsafe.Pointer(in.Resources))
	out.AuxResources = (*corev1.ResourceRequirements)(unsafe.Pointer(in.AuxResources))
	out.Tolerations = *(*[]corev1.Toleration)(unsafe.Pointer(&in.Tolerations))
	out.PriorityClassName = in.PriorityClassName
	return nil
}

// Convert_cstor_PoolConfig_To_v1_PoolConfig is an autogenerated conversion function.
func Convert_cstor_PoolConfig_To_v1_PoolConfig(in *cstor.PoolConfig, out *v1.PoolConfig, s conversion.Scope) error {
	return autoConvert_cstor_PoolConfig_To_v1_PoolConfig(in, out, s)
}

func autoConvert_v1_PoolSpec_To_cstor_PoolSpec(in *v1.PoolSpec, out *cstor.PoolSpec, s conversion.Scope) error {
	out.NodeSelector = *(*map[string]string)(unsafe.Pointer(&in.NodeSelector))
	out.DataRaidGroups = *(*[]cstor.RaidGroup)(unsafe.Pointer(&in.DataRaidGroups))
	out.WriteCacheRaidGroups = *(*[]cstor.RaidGroup)(unsafe.Pointer(&in.WriteCacheRaidGroups))
	if err := Convert_v1_PoolConfig_To_cstor_PoolConfig(&in.PoolConfig, &out.PoolConfig, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_PoolSpec_To_cstor_PoolSpec is an autogenerated conversion function.
func Convert_v1_PoolSpec_To_cstor_PoolSpec(in *v1.PoolSpec, out *cstor.PoolSpec, s conversion.Scope) error {
	return autoConvert_v1_PoolSpec_To_cstor_PoolSpec(in, out, s)
}

func autoConvert_cstor_PoolSpec_To_v1_PoolSpec(in *cstor.PoolSpec, out *v1.PoolSpec, s conversion.Scope) error {
	out.NodeSelector = *(*map[string]string)(unsafe.Pointer(&in.NodeSelector))
	out.DataRaidGroups = *(*[]v1.RaidGroup)(unsafe.Pointer(&in.DataRaidGroups))
	out.WriteCacheRaidGroups = *(*[]v1.RaidGroup)(unsafe.Pointer(&in.WriteCacheRaidGroups))
	if err := Convert_cstor_PoolConfig_To_v1_PoolConfig(&in.PoolConfig, &out.PoolConfig, s); err != nil {
		return err
	}
	return nil
}

// Convert_cstor_PoolSpec_To_v1_PoolSpec is an autogenerated conversion function.
func Convert_cstor_PoolSpec_To_v1_PoolSpec(in *cstor.PoolSpec, out *v1.PoolSpec, s conversion.Scope) error {
	return autoConvert_cstor_PoolSpec_To_v1_PoolSpec(in, out, s)
}

func autoConvert_v1_RaidGroup_To_cstor_RaidGroup(in *v1.RaidGroup, out *cstor.RaidGroup, s conversion.Scope) error {
	out.BlockDevices = *(*[]cstor.CStorPoolClusterBlockDevice)(unsafe.Pointer(&in.BlockDevices))
	return nil
}

// Convert_v1_RaidGroup_To_cstor_RaidGroup is an autogenerated conversion function.
func Convert_v1_RaidGroup_To_cstor_RaidGroup(in *v1.RaidGroup, out *cstor.RaidGroup, s conversion.Scope) error {
	return autoConvert_v1_RaidGroup_To_cstor_RaidGroup(in, out, s)
}

func autoConvert_cstor_RaidGroup_To_v1_RaidGroup(in *cstor.RaidGroup, out *v1.RaidGroup, s conversion.Scope) error {
	out.BlockDevices = *(*[]v1.CStorPoolClusterBlockDevice)(unsafe.Pointer(&in.BlockDevices))
	return nil
}

// Convert_cstor_RaidGroup_To_v1_RaidGroup is an autogenerated conversion function.
func Convert_cstor_RaidGroup_To_v1_RaidGroup(in *cstor.RaidGroup, out *v1.RaidGroup, s conversion.Scope) error {
	return autoConvert_cstor_RaidGroup_To_v1_RaidGroup(in, out, s)
}

func autoConvert_v1_VersionDetails_To_cstor_VersionDetails(in *v1.VersionDetails, out *cstor.VersionDetails, s conversion.Scope) error {
	out.AutoUpgrade = in.AutoUpgrade
	out.Desired = in.Desired
	if err := Convert_v1_VersionStatus_To_cstor_VersionStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_VersionDetails_To_cstor_VersionDetails is an autogenerated conversion function.
func Convert_v1_VersionDetails_To_cstor_VersionDetails(in *v1.VersionDetails, out *cstor.VersionDetails, s conversion.Scope) error {
	return autoConvert_v1_VersionDetails_To_cstor_VersionDetails(in, out, s)
}

func autoConvert_cstor_VersionDetails_To_v1_VersionDetails(in *cstor.VersionDetails, out *v1.VersionDetails, s conversion.Scope) error {
	out.AutoUpgrade = in.AutoUpgrade
	out.Desired = in.Desired
	if err := Convert_cstor_VersionStatus_To_v1_VersionStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_cstor_VersionDetails_To_v1_VersionDetails is an autogenerated conversion function.
func Convert_cstor_VersionDetails_To_v1_VersionDetails(in *cstor.VersionDetails, out *v1.VersionDetails, s conversion.Scope) error {
	return autoConvert_cstor_VersionDetails_To_v1_VersionDetails(in, out, s)
}

func autoConvert_v1_VersionStatus_To_cstor_VersionStatus(in *v1.VersionStatus, out *cstor.VersionStatus, s conversion.Scope) error {
	out.DependentsUpgraded = in.DependentsUpgraded
	out.Current = in.Current
	out.State = cstor.VersionState(in.State)
	out.Message = in.Message
	out.Reason = in.Reason
	out.LastUpdateTime = in.LastUpdateTime
	return nil
}

// Convert_v1_VersionStatus_To_cstor_VersionStatus is an autogenerated conversion function.
func Convert_v1_VersionStatus_To_cstor_VersionStatus(in *v1.VersionStatus, out *cstor.VersionStatus, s conversion.Scope) error {
	return autoConvert_v1_VersionStatus_To_cstor_VersionStatus(in, out, s)
}

func autoConvert_cstor_VersionStatus_To_v1_VersionStatus(in *cstor.VersionStatus, out *v1.VersionStatus, s conversion.Scope) error {
	out.DependentsUpgraded = in.DependentsUpgraded
	out.Current = in.Current
	out.State = v1.VersionState(in.State)
	out.Message = in.Message
	out.Reason = in.Reason
	out.LastUpdateTime = in.LastUpdateTime
	return nil
}

// Convert_cstor_VersionStatus_To_v1_VersionStatus is an autogenerated conversion function.
func Convert_cstor_VersionStatus_To_v1_VersionStatus(in *cstor.VersionStatus, out *v1.VersionStatus, s conversion.Scope) error {
	return autoConvert_cstor_VersionStatus_To_v1_VersionStatus(in, out, s)
}
