// +build !ignore_autogenerated

/*
Copyright 2020 The OpenEBS Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	v1alpha1 "github.com/openebs/api/pkg/apis/openebs.io/v1alpha1"
	openebsio "github.com/openebs/api/pkg/internalapis/apis/openebs.io"
	v1 "k8s.io/api/core/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*v1alpha1.BlockDevice)(nil), (*openebsio.BlockDevice)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BlockDevice_To_openebsio_BlockDevice(a.(*v1alpha1.BlockDevice), b.(*openebsio.BlockDevice), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openebsio.BlockDevice)(nil), (*v1alpha1.BlockDevice)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openebsio_BlockDevice_To_v1alpha1_BlockDevice(a.(*openebsio.BlockDevice), b.(*v1alpha1.BlockDevice), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.BlockDeviceClaim)(nil), (*openebsio.BlockDeviceClaim)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BlockDeviceClaim_To_openebsio_BlockDeviceClaim(a.(*v1alpha1.BlockDeviceClaim), b.(*openebsio.BlockDeviceClaim), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openebsio.BlockDeviceClaim)(nil), (*v1alpha1.BlockDeviceClaim)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openebsio_BlockDeviceClaim_To_v1alpha1_BlockDeviceClaim(a.(*openebsio.BlockDeviceClaim), b.(*v1alpha1.BlockDeviceClaim), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.BlockDeviceClaimList)(nil), (*openebsio.BlockDeviceClaimList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BlockDeviceClaimList_To_openebsio_BlockDeviceClaimList(a.(*v1alpha1.BlockDeviceClaimList), b.(*openebsio.BlockDeviceClaimList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openebsio.BlockDeviceClaimList)(nil), (*v1alpha1.BlockDeviceClaimList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openebsio_BlockDeviceClaimList_To_v1alpha1_BlockDeviceClaimList(a.(*openebsio.BlockDeviceClaimList), b.(*v1alpha1.BlockDeviceClaimList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.BlockDeviceList)(nil), (*openebsio.BlockDeviceList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BlockDeviceList_To_openebsio_BlockDeviceList(a.(*v1alpha1.BlockDeviceList), b.(*openebsio.BlockDeviceList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openebsio.BlockDeviceList)(nil), (*v1alpha1.BlockDeviceList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openebsio_BlockDeviceList_To_v1alpha1_BlockDeviceList(a.(*openebsio.BlockDeviceList), b.(*v1alpha1.BlockDeviceList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.BlockDeviceNodeAttributes)(nil), (*openebsio.BlockDeviceNodeAttributes)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BlockDeviceNodeAttributes_To_openebsio_BlockDeviceNodeAttributes(a.(*v1alpha1.BlockDeviceNodeAttributes), b.(*openebsio.BlockDeviceNodeAttributes), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openebsio.BlockDeviceNodeAttributes)(nil), (*v1alpha1.BlockDeviceNodeAttributes)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openebsio_BlockDeviceNodeAttributes_To_v1alpha1_BlockDeviceNodeAttributes(a.(*openebsio.BlockDeviceNodeAttributes), b.(*v1alpha1.BlockDeviceNodeAttributes), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.DeviceCapacity)(nil), (*openebsio.DeviceCapacity)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DeviceCapacity_To_openebsio_DeviceCapacity(a.(*v1alpha1.DeviceCapacity), b.(*openebsio.DeviceCapacity), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openebsio.DeviceCapacity)(nil), (*v1alpha1.DeviceCapacity)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openebsio_DeviceCapacity_To_v1alpha1_DeviceCapacity(a.(*openebsio.DeviceCapacity), b.(*v1alpha1.DeviceCapacity), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.DeviceClaimDetails)(nil), (*openebsio.DeviceClaimDetails)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DeviceClaimDetails_To_openebsio_DeviceClaimDetails(a.(*v1alpha1.DeviceClaimDetails), b.(*openebsio.DeviceClaimDetails), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openebsio.DeviceClaimDetails)(nil), (*v1alpha1.DeviceClaimDetails)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openebsio_DeviceClaimDetails_To_v1alpha1_DeviceClaimDetails(a.(*openebsio.DeviceClaimDetails), b.(*v1alpha1.DeviceClaimDetails), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.DeviceClaimResources)(nil), (*openebsio.DeviceClaimResources)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DeviceClaimResources_To_openebsio_DeviceClaimResources(a.(*v1alpha1.DeviceClaimResources), b.(*openebsio.DeviceClaimResources), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openebsio.DeviceClaimResources)(nil), (*v1alpha1.DeviceClaimResources)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openebsio_DeviceClaimResources_To_v1alpha1_DeviceClaimResources(a.(*openebsio.DeviceClaimResources), b.(*v1alpha1.DeviceClaimResources), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.DeviceClaimSpec)(nil), (*openebsio.DeviceClaimSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DeviceClaimSpec_To_openebsio_DeviceClaimSpec(a.(*v1alpha1.DeviceClaimSpec), b.(*openebsio.DeviceClaimSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openebsio.DeviceClaimSpec)(nil), (*v1alpha1.DeviceClaimSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openebsio_DeviceClaimSpec_To_v1alpha1_DeviceClaimSpec(a.(*openebsio.DeviceClaimSpec), b.(*v1alpha1.DeviceClaimSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.DeviceClaimStatus)(nil), (*openebsio.DeviceClaimStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DeviceClaimStatus_To_openebsio_DeviceClaimStatus(a.(*v1alpha1.DeviceClaimStatus), b.(*openebsio.DeviceClaimStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openebsio.DeviceClaimStatus)(nil), (*v1alpha1.DeviceClaimStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openebsio_DeviceClaimStatus_To_v1alpha1_DeviceClaimStatus(a.(*openebsio.DeviceClaimStatus), b.(*v1alpha1.DeviceClaimStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.DeviceDetails)(nil), (*openebsio.DeviceDetails)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DeviceDetails_To_openebsio_DeviceDetails(a.(*v1alpha1.DeviceDetails), b.(*openebsio.DeviceDetails), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openebsio.DeviceDetails)(nil), (*v1alpha1.DeviceDetails)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openebsio_DeviceDetails_To_v1alpha1_DeviceDetails(a.(*openebsio.DeviceDetails), b.(*v1alpha1.DeviceDetails), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.DeviceDevLink)(nil), (*openebsio.DeviceDevLink)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DeviceDevLink_To_openebsio_DeviceDevLink(a.(*v1alpha1.DeviceDevLink), b.(*openebsio.DeviceDevLink), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openebsio.DeviceDevLink)(nil), (*v1alpha1.DeviceDevLink)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openebsio_DeviceDevLink_To_v1alpha1_DeviceDevLink(a.(*openebsio.DeviceDevLink), b.(*v1alpha1.DeviceDevLink), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.DeviceSpec)(nil), (*openebsio.DeviceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DeviceSpec_To_openebsio_DeviceSpec(a.(*v1alpha1.DeviceSpec), b.(*openebsio.DeviceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openebsio.DeviceSpec)(nil), (*v1alpha1.DeviceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openebsio_DeviceSpec_To_v1alpha1_DeviceSpec(a.(*openebsio.DeviceSpec), b.(*v1alpha1.DeviceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.DeviceStatus)(nil), (*openebsio.DeviceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DeviceStatus_To_openebsio_DeviceStatus(a.(*v1alpha1.DeviceStatus), b.(*openebsio.DeviceStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openebsio.DeviceStatus)(nil), (*v1alpha1.DeviceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openebsio_DeviceStatus_To_v1alpha1_DeviceStatus(a.(*openebsio.DeviceStatus), b.(*v1alpha1.DeviceStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.FileSystemInfo)(nil), (*openebsio.FileSystemInfo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_FileSystemInfo_To_openebsio_FileSystemInfo(a.(*v1alpha1.FileSystemInfo), b.(*openebsio.FileSystemInfo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openebsio.FileSystemInfo)(nil), (*v1alpha1.FileSystemInfo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openebsio_FileSystemInfo_To_v1alpha1_FileSystemInfo(a.(*openebsio.FileSystemInfo), b.(*v1alpha1.FileSystemInfo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.NodeAttribute)(nil), (*openebsio.NodeAttribute)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NodeAttribute_To_openebsio_NodeAttribute(a.(*v1alpha1.NodeAttribute), b.(*openebsio.NodeAttribute), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*openebsio.NodeAttribute)(nil), (*v1alpha1.NodeAttribute)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_openebsio_NodeAttribute_To_v1alpha1_NodeAttribute(a.(*openebsio.NodeAttribute), b.(*v1alpha1.NodeAttribute), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_BlockDevice_To_openebsio_BlockDevice(in *v1alpha1.BlockDevice, out *openebsio.BlockDevice, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_DeviceSpec_To_openebsio_DeviceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_DeviceStatus_To_openebsio_DeviceStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_BlockDevice_To_openebsio_BlockDevice is an autogenerated conversion function.
func Convert_v1alpha1_BlockDevice_To_openebsio_BlockDevice(in *v1alpha1.BlockDevice, out *openebsio.BlockDevice, s conversion.Scope) error {
	return autoConvert_v1alpha1_BlockDevice_To_openebsio_BlockDevice(in, out, s)
}

func autoConvert_openebsio_BlockDevice_To_v1alpha1_BlockDevice(in *openebsio.BlockDevice, out *v1alpha1.BlockDevice, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_openebsio_DeviceSpec_To_v1alpha1_DeviceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_openebsio_DeviceStatus_To_v1alpha1_DeviceStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_openebsio_BlockDevice_To_v1alpha1_BlockDevice is an autogenerated conversion function.
func Convert_openebsio_BlockDevice_To_v1alpha1_BlockDevice(in *openebsio.BlockDevice, out *v1alpha1.BlockDevice, s conversion.Scope) error {
	return autoConvert_openebsio_BlockDevice_To_v1alpha1_BlockDevice(in, out, s)
}

func autoConvert_v1alpha1_BlockDeviceClaim_To_openebsio_BlockDeviceClaim(in *v1alpha1.BlockDeviceClaim, out *openebsio.BlockDeviceClaim, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_DeviceClaimSpec_To_openebsio_DeviceClaimSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_DeviceClaimStatus_To_openebsio_DeviceClaimStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_BlockDeviceClaim_To_openebsio_BlockDeviceClaim is an autogenerated conversion function.
func Convert_v1alpha1_BlockDeviceClaim_To_openebsio_BlockDeviceClaim(in *v1alpha1.BlockDeviceClaim, out *openebsio.BlockDeviceClaim, s conversion.Scope) error {
	return autoConvert_v1alpha1_BlockDeviceClaim_To_openebsio_BlockDeviceClaim(in, out, s)
}

func autoConvert_openebsio_BlockDeviceClaim_To_v1alpha1_BlockDeviceClaim(in *openebsio.BlockDeviceClaim, out *v1alpha1.BlockDeviceClaim, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_openebsio_DeviceClaimSpec_To_v1alpha1_DeviceClaimSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_openebsio_DeviceClaimStatus_To_v1alpha1_DeviceClaimStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_openebsio_BlockDeviceClaim_To_v1alpha1_BlockDeviceClaim is an autogenerated conversion function.
func Convert_openebsio_BlockDeviceClaim_To_v1alpha1_BlockDeviceClaim(in *openebsio.BlockDeviceClaim, out *v1alpha1.BlockDeviceClaim, s conversion.Scope) error {
	return autoConvert_openebsio_BlockDeviceClaim_To_v1alpha1_BlockDeviceClaim(in, out, s)
}

func autoConvert_v1alpha1_BlockDeviceClaimList_To_openebsio_BlockDeviceClaimList(in *v1alpha1.BlockDeviceClaimList, out *openebsio.BlockDeviceClaimList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]openebsio.BlockDeviceClaim)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_BlockDeviceClaimList_To_openebsio_BlockDeviceClaimList is an autogenerated conversion function.
func Convert_v1alpha1_BlockDeviceClaimList_To_openebsio_BlockDeviceClaimList(in *v1alpha1.BlockDeviceClaimList, out *openebsio.BlockDeviceClaimList, s conversion.Scope) error {
	return autoConvert_v1alpha1_BlockDeviceClaimList_To_openebsio_BlockDeviceClaimList(in, out, s)
}

func autoConvert_openebsio_BlockDeviceClaimList_To_v1alpha1_BlockDeviceClaimList(in *openebsio.BlockDeviceClaimList, out *v1alpha1.BlockDeviceClaimList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1alpha1.BlockDeviceClaim)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_openebsio_BlockDeviceClaimList_To_v1alpha1_BlockDeviceClaimList is an autogenerated conversion function.
func Convert_openebsio_BlockDeviceClaimList_To_v1alpha1_BlockDeviceClaimList(in *openebsio.BlockDeviceClaimList, out *v1alpha1.BlockDeviceClaimList, s conversion.Scope) error {
	return autoConvert_openebsio_BlockDeviceClaimList_To_v1alpha1_BlockDeviceClaimList(in, out, s)
}

func autoConvert_v1alpha1_BlockDeviceList_To_openebsio_BlockDeviceList(in *v1alpha1.BlockDeviceList, out *openebsio.BlockDeviceList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]openebsio.BlockDevice)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_BlockDeviceList_To_openebsio_BlockDeviceList is an autogenerated conversion function.
func Convert_v1alpha1_BlockDeviceList_To_openebsio_BlockDeviceList(in *v1alpha1.BlockDeviceList, out *openebsio.BlockDeviceList, s conversion.Scope) error {
	return autoConvert_v1alpha1_BlockDeviceList_To_openebsio_BlockDeviceList(in, out, s)
}

func autoConvert_openebsio_BlockDeviceList_To_v1alpha1_BlockDeviceList(in *openebsio.BlockDeviceList, out *v1alpha1.BlockDeviceList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1alpha1.BlockDevice)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_openebsio_BlockDeviceList_To_v1alpha1_BlockDeviceList is an autogenerated conversion function.
func Convert_openebsio_BlockDeviceList_To_v1alpha1_BlockDeviceList(in *openebsio.BlockDeviceList, out *v1alpha1.BlockDeviceList, s conversion.Scope) error {
	return autoConvert_openebsio_BlockDeviceList_To_v1alpha1_BlockDeviceList(in, out, s)
}

func autoConvert_v1alpha1_BlockDeviceNodeAttributes_To_openebsio_BlockDeviceNodeAttributes(in *v1alpha1.BlockDeviceNodeAttributes, out *openebsio.BlockDeviceNodeAttributes, s conversion.Scope) error {
	out.NodeName = in.NodeName
	out.HostName = in.HostName
	return nil
}

// Convert_v1alpha1_BlockDeviceNodeAttributes_To_openebsio_BlockDeviceNodeAttributes is an autogenerated conversion function.
func Convert_v1alpha1_BlockDeviceNodeAttributes_To_openebsio_BlockDeviceNodeAttributes(in *v1alpha1.BlockDeviceNodeAttributes, out *openebsio.BlockDeviceNodeAttributes, s conversion.Scope) error {
	return autoConvert_v1alpha1_BlockDeviceNodeAttributes_To_openebsio_BlockDeviceNodeAttributes(in, out, s)
}

func autoConvert_openebsio_BlockDeviceNodeAttributes_To_v1alpha1_BlockDeviceNodeAttributes(in *openebsio.BlockDeviceNodeAttributes, out *v1alpha1.BlockDeviceNodeAttributes, s conversion.Scope) error {
	out.NodeName = in.NodeName
	out.HostName = in.HostName
	return nil
}

// Convert_openebsio_BlockDeviceNodeAttributes_To_v1alpha1_BlockDeviceNodeAttributes is an autogenerated conversion function.
func Convert_openebsio_BlockDeviceNodeAttributes_To_v1alpha1_BlockDeviceNodeAttributes(in *openebsio.BlockDeviceNodeAttributes, out *v1alpha1.BlockDeviceNodeAttributes, s conversion.Scope) error {
	return autoConvert_openebsio_BlockDeviceNodeAttributes_To_v1alpha1_BlockDeviceNodeAttributes(in, out, s)
}

func autoConvert_v1alpha1_DeviceCapacity_To_openebsio_DeviceCapacity(in *v1alpha1.DeviceCapacity, out *openebsio.DeviceCapacity, s conversion.Scope) error {
	out.Storage = in.Storage
	out.PhysicalSectorSize = in.PhysicalSectorSize
	out.LogicalSectorSize = in.LogicalSectorSize
	return nil
}

// Convert_v1alpha1_DeviceCapacity_To_openebsio_DeviceCapacity is an autogenerated conversion function.
func Convert_v1alpha1_DeviceCapacity_To_openebsio_DeviceCapacity(in *v1alpha1.DeviceCapacity, out *openebsio.DeviceCapacity, s conversion.Scope) error {
	return autoConvert_v1alpha1_DeviceCapacity_To_openebsio_DeviceCapacity(in, out, s)
}

func autoConvert_openebsio_DeviceCapacity_To_v1alpha1_DeviceCapacity(in *openebsio.DeviceCapacity, out *v1alpha1.DeviceCapacity, s conversion.Scope) error {
	out.Storage = in.Storage
	out.PhysicalSectorSize = in.PhysicalSectorSize
	out.LogicalSectorSize = in.LogicalSectorSize
	return nil
}

// Convert_openebsio_DeviceCapacity_To_v1alpha1_DeviceCapacity is an autogenerated conversion function.
func Convert_openebsio_DeviceCapacity_To_v1alpha1_DeviceCapacity(in *openebsio.DeviceCapacity, out *v1alpha1.DeviceCapacity, s conversion.Scope) error {
	return autoConvert_openebsio_DeviceCapacity_To_v1alpha1_DeviceCapacity(in, out, s)
}

func autoConvert_v1alpha1_DeviceClaimDetails_To_openebsio_DeviceClaimDetails(in *v1alpha1.DeviceClaimDetails, out *openebsio.DeviceClaimDetails, s conversion.Scope) error {
	out.BlockVolumeMode = openebsio.BlockDeviceVolumeMode(in.BlockVolumeMode)
	out.DeviceFormat = in.DeviceFormat
	out.AllowPartition = in.AllowPartition
	return nil
}

// Convert_v1alpha1_DeviceClaimDetails_To_openebsio_DeviceClaimDetails is an autogenerated conversion function.
func Convert_v1alpha1_DeviceClaimDetails_To_openebsio_DeviceClaimDetails(in *v1alpha1.DeviceClaimDetails, out *openebsio.DeviceClaimDetails, s conversion.Scope) error {
	return autoConvert_v1alpha1_DeviceClaimDetails_To_openebsio_DeviceClaimDetails(in, out, s)
}

func autoConvert_openebsio_DeviceClaimDetails_To_v1alpha1_DeviceClaimDetails(in *openebsio.DeviceClaimDetails, out *v1alpha1.DeviceClaimDetails, s conversion.Scope) error {
	out.BlockVolumeMode = v1alpha1.BlockDeviceVolumeMode(in.BlockVolumeMode)
	out.DeviceFormat = in.DeviceFormat
	out.AllowPartition = in.AllowPartition
	return nil
}

// Convert_openebsio_DeviceClaimDetails_To_v1alpha1_DeviceClaimDetails is an autogenerated conversion function.
func Convert_openebsio_DeviceClaimDetails_To_v1alpha1_DeviceClaimDetails(in *openebsio.DeviceClaimDetails, out *v1alpha1.DeviceClaimDetails, s conversion.Scope) error {
	return autoConvert_openebsio_DeviceClaimDetails_To_v1alpha1_DeviceClaimDetails(in, out, s)
}

func autoConvert_v1alpha1_DeviceClaimResources_To_openebsio_DeviceClaimResources(in *v1alpha1.DeviceClaimResources, out *openebsio.DeviceClaimResources, s conversion.Scope) error {
	out.Requests = *(*v1.ResourceList)(unsafe.Pointer(&in.Requests))
	return nil
}

// Convert_v1alpha1_DeviceClaimResources_To_openebsio_DeviceClaimResources is an autogenerated conversion function.
func Convert_v1alpha1_DeviceClaimResources_To_openebsio_DeviceClaimResources(in *v1alpha1.DeviceClaimResources, out *openebsio.DeviceClaimResources, s conversion.Scope) error {
	return autoConvert_v1alpha1_DeviceClaimResources_To_openebsio_DeviceClaimResources(in, out, s)
}

func autoConvert_openebsio_DeviceClaimResources_To_v1alpha1_DeviceClaimResources(in *openebsio.DeviceClaimResources, out *v1alpha1.DeviceClaimResources, s conversion.Scope) error {
	out.Requests = *(*v1.ResourceList)(unsafe.Pointer(&in.Requests))
	return nil
}

// Convert_openebsio_DeviceClaimResources_To_v1alpha1_DeviceClaimResources is an autogenerated conversion function.
func Convert_openebsio_DeviceClaimResources_To_v1alpha1_DeviceClaimResources(in *openebsio.DeviceClaimResources, out *v1alpha1.DeviceClaimResources, s conversion.Scope) error {
	return autoConvert_openebsio_DeviceClaimResources_To_v1alpha1_DeviceClaimResources(in, out, s)
}

func autoConvert_v1alpha1_DeviceClaimSpec_To_openebsio_DeviceClaimSpec(in *v1alpha1.DeviceClaimSpec, out *openebsio.DeviceClaimSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_DeviceClaimResources_To_openebsio_DeviceClaimResources(&in.Resources, &out.Resources, s); err != nil {
		return err
	}
	out.DeviceType = in.DeviceType
	out.HostName = in.HostName
	if err := Convert_v1alpha1_DeviceClaimDetails_To_openebsio_DeviceClaimDetails(&in.Details, &out.Details, s); err != nil {
		return err
	}
	out.BlockDeviceName = in.BlockDeviceName
	if err := Convert_v1alpha1_BlockDeviceNodeAttributes_To_openebsio_BlockDeviceNodeAttributes(&in.BlockDeviceNodeAttributes, &out.BlockDeviceNodeAttributes, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_DeviceClaimSpec_To_openebsio_DeviceClaimSpec is an autogenerated conversion function.
func Convert_v1alpha1_DeviceClaimSpec_To_openebsio_DeviceClaimSpec(in *v1alpha1.DeviceClaimSpec, out *openebsio.DeviceClaimSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_DeviceClaimSpec_To_openebsio_DeviceClaimSpec(in, out, s)
}

func autoConvert_openebsio_DeviceClaimSpec_To_v1alpha1_DeviceClaimSpec(in *openebsio.DeviceClaimSpec, out *v1alpha1.DeviceClaimSpec, s conversion.Scope) error {
	if err := Convert_openebsio_DeviceClaimResources_To_v1alpha1_DeviceClaimResources(&in.Resources, &out.Resources, s); err != nil {
		return err
	}
	out.DeviceType = in.DeviceType
	out.HostName = in.HostName
	if err := Convert_openebsio_DeviceClaimDetails_To_v1alpha1_DeviceClaimDetails(&in.Details, &out.Details, s); err != nil {
		return err
	}
	out.BlockDeviceName = in.BlockDeviceName
	if err := Convert_openebsio_BlockDeviceNodeAttributes_To_v1alpha1_BlockDeviceNodeAttributes(&in.BlockDeviceNodeAttributes, &out.BlockDeviceNodeAttributes, s); err != nil {
		return err
	}
	return nil
}

// Convert_openebsio_DeviceClaimSpec_To_v1alpha1_DeviceClaimSpec is an autogenerated conversion function.
func Convert_openebsio_DeviceClaimSpec_To_v1alpha1_DeviceClaimSpec(in *openebsio.DeviceClaimSpec, out *v1alpha1.DeviceClaimSpec, s conversion.Scope) error {
	return autoConvert_openebsio_DeviceClaimSpec_To_v1alpha1_DeviceClaimSpec(in, out, s)
}

func autoConvert_v1alpha1_DeviceClaimStatus_To_openebsio_DeviceClaimStatus(in *v1alpha1.DeviceClaimStatus, out *openebsio.DeviceClaimStatus, s conversion.Scope) error {
	out.Phase = openebsio.DeviceClaimPhase(in.Phase)
	return nil
}

// Convert_v1alpha1_DeviceClaimStatus_To_openebsio_DeviceClaimStatus is an autogenerated conversion function.
func Convert_v1alpha1_DeviceClaimStatus_To_openebsio_DeviceClaimStatus(in *v1alpha1.DeviceClaimStatus, out *openebsio.DeviceClaimStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_DeviceClaimStatus_To_openebsio_DeviceClaimStatus(in, out, s)
}

func autoConvert_openebsio_DeviceClaimStatus_To_v1alpha1_DeviceClaimStatus(in *openebsio.DeviceClaimStatus, out *v1alpha1.DeviceClaimStatus, s conversion.Scope) error {
	out.Phase = v1alpha1.DeviceClaimPhase(in.Phase)
	return nil
}

// Convert_openebsio_DeviceClaimStatus_To_v1alpha1_DeviceClaimStatus is an autogenerated conversion function.
func Convert_openebsio_DeviceClaimStatus_To_v1alpha1_DeviceClaimStatus(in *openebsio.DeviceClaimStatus, out *v1alpha1.DeviceClaimStatus, s conversion.Scope) error {
	return autoConvert_openebsio_DeviceClaimStatus_To_v1alpha1_DeviceClaimStatus(in, out, s)
}

func autoConvert_v1alpha1_DeviceDetails_To_openebsio_DeviceDetails(in *v1alpha1.DeviceDetails, out *openebsio.DeviceDetails, s conversion.Scope) error {
	out.DeviceType = in.DeviceType
	out.DriveType = in.DriveType
	out.LogicalBlockSize = in.LogicalBlockSize
	out.PhysicalBlockSize = in.PhysicalBlockSize
	out.HardwareSectorSize = in.HardwareSectorSize
	out.Model = in.Model
	out.Compliance = in.Compliance
	out.Serial = in.Serial
	out.Vendor = in.Vendor
	out.FirmwareRevision = in.FirmwareRevision
	return nil
}

// Convert_v1alpha1_DeviceDetails_To_openebsio_DeviceDetails is an autogenerated conversion function.
func Convert_v1alpha1_DeviceDetails_To_openebsio_DeviceDetails(in *v1alpha1.DeviceDetails, out *openebsio.DeviceDetails, s conversion.Scope) error {
	return autoConvert_v1alpha1_DeviceDetails_To_openebsio_DeviceDetails(in, out, s)
}

func autoConvert_openebsio_DeviceDetails_To_v1alpha1_DeviceDetails(in *openebsio.DeviceDetails, out *v1alpha1.DeviceDetails, s conversion.Scope) error {
	out.DeviceType = in.DeviceType
	out.DriveType = in.DriveType
	out.LogicalBlockSize = in.LogicalBlockSize
	out.PhysicalBlockSize = in.PhysicalBlockSize
	out.HardwareSectorSize = in.HardwareSectorSize
	out.Model = in.Model
	out.Compliance = in.Compliance
	out.Serial = in.Serial
	out.Vendor = in.Vendor
	out.FirmwareRevision = in.FirmwareRevision
	return nil
}

// Convert_openebsio_DeviceDetails_To_v1alpha1_DeviceDetails is an autogenerated conversion function.
func Convert_openebsio_DeviceDetails_To_v1alpha1_DeviceDetails(in *openebsio.DeviceDetails, out *v1alpha1.DeviceDetails, s conversion.Scope) error {
	return autoConvert_openebsio_DeviceDetails_To_v1alpha1_DeviceDetails(in, out, s)
}

func autoConvert_v1alpha1_DeviceDevLink_To_openebsio_DeviceDevLink(in *v1alpha1.DeviceDevLink, out *openebsio.DeviceDevLink, s conversion.Scope) error {
	out.Kind = in.Kind
	out.Links = *(*[]string)(unsafe.Pointer(&in.Links))
	return nil
}

// Convert_v1alpha1_DeviceDevLink_To_openebsio_DeviceDevLink is an autogenerated conversion function.
func Convert_v1alpha1_DeviceDevLink_To_openebsio_DeviceDevLink(in *v1alpha1.DeviceDevLink, out *openebsio.DeviceDevLink, s conversion.Scope) error {
	return autoConvert_v1alpha1_DeviceDevLink_To_openebsio_DeviceDevLink(in, out, s)
}

func autoConvert_openebsio_DeviceDevLink_To_v1alpha1_DeviceDevLink(in *openebsio.DeviceDevLink, out *v1alpha1.DeviceDevLink, s conversion.Scope) error {
	out.Kind = in.Kind
	out.Links = *(*[]string)(unsafe.Pointer(&in.Links))
	return nil
}

// Convert_openebsio_DeviceDevLink_To_v1alpha1_DeviceDevLink is an autogenerated conversion function.
func Convert_openebsio_DeviceDevLink_To_v1alpha1_DeviceDevLink(in *openebsio.DeviceDevLink, out *v1alpha1.DeviceDevLink, s conversion.Scope) error {
	return autoConvert_openebsio_DeviceDevLink_To_v1alpha1_DeviceDevLink(in, out, s)
}

func autoConvert_v1alpha1_DeviceSpec_To_openebsio_DeviceSpec(in *v1alpha1.DeviceSpec, out *openebsio.DeviceSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_NodeAttribute_To_openebsio_NodeAttribute(&in.NodeAttributes, &out.NodeAttributes, s); err != nil {
		return err
	}
	out.Path = in.Path
	if err := Convert_v1alpha1_DeviceCapacity_To_openebsio_DeviceCapacity(&in.Capacity, &out.Capacity, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_DeviceDetails_To_openebsio_DeviceDetails(&in.Details, &out.Details, s); err != nil {
		return err
	}
	out.ClaimRef = (*v1.ObjectReference)(unsafe.Pointer(in.ClaimRef))
	out.DevLinks = *(*[]openebsio.DeviceDevLink)(unsafe.Pointer(&in.DevLinks))
	if err := Convert_v1alpha1_FileSystemInfo_To_openebsio_FileSystemInfo(&in.FileSystem, &out.FileSystem, s); err != nil {
		return err
	}
	out.Partitioned = in.Partitioned
	out.ParentDevice = in.ParentDevice
	out.AggregateDevice = in.AggregateDevice
	return nil
}

// Convert_v1alpha1_DeviceSpec_To_openebsio_DeviceSpec is an autogenerated conversion function.
func Convert_v1alpha1_DeviceSpec_To_openebsio_DeviceSpec(in *v1alpha1.DeviceSpec, out *openebsio.DeviceSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_DeviceSpec_To_openebsio_DeviceSpec(in, out, s)
}

func autoConvert_openebsio_DeviceSpec_To_v1alpha1_DeviceSpec(in *openebsio.DeviceSpec, out *v1alpha1.DeviceSpec, s conversion.Scope) error {
	if err := Convert_openebsio_NodeAttribute_To_v1alpha1_NodeAttribute(&in.NodeAttributes, &out.NodeAttributes, s); err != nil {
		return err
	}
	out.Path = in.Path
	if err := Convert_openebsio_DeviceCapacity_To_v1alpha1_DeviceCapacity(&in.Capacity, &out.Capacity, s); err != nil {
		return err
	}
	if err := Convert_openebsio_DeviceDetails_To_v1alpha1_DeviceDetails(&in.Details, &out.Details, s); err != nil {
		return err
	}
	out.ClaimRef = (*v1.ObjectReference)(unsafe.Pointer(in.ClaimRef))
	out.DevLinks = *(*[]v1alpha1.DeviceDevLink)(unsafe.Pointer(&in.DevLinks))
	if err := Convert_openebsio_FileSystemInfo_To_v1alpha1_FileSystemInfo(&in.FileSystem, &out.FileSystem, s); err != nil {
		return err
	}
	out.Partitioned = in.Partitioned
	out.ParentDevice = in.ParentDevice
	out.AggregateDevice = in.AggregateDevice
	return nil
}

// Convert_openebsio_DeviceSpec_To_v1alpha1_DeviceSpec is an autogenerated conversion function.
func Convert_openebsio_DeviceSpec_To_v1alpha1_DeviceSpec(in *openebsio.DeviceSpec, out *v1alpha1.DeviceSpec, s conversion.Scope) error {
	return autoConvert_openebsio_DeviceSpec_To_v1alpha1_DeviceSpec(in, out, s)
}

func autoConvert_v1alpha1_DeviceStatus_To_openebsio_DeviceStatus(in *v1alpha1.DeviceStatus, out *openebsio.DeviceStatus, s conversion.Scope) error {
	out.ClaimState = openebsio.DeviceClaimState(in.ClaimState)
	out.State = openebsio.BlockDeviceState(in.State)
	return nil
}

// Convert_v1alpha1_DeviceStatus_To_openebsio_DeviceStatus is an autogenerated conversion function.
func Convert_v1alpha1_DeviceStatus_To_openebsio_DeviceStatus(in *v1alpha1.DeviceStatus, out *openebsio.DeviceStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_DeviceStatus_To_openebsio_DeviceStatus(in, out, s)
}

func autoConvert_openebsio_DeviceStatus_To_v1alpha1_DeviceStatus(in *openebsio.DeviceStatus, out *v1alpha1.DeviceStatus, s conversion.Scope) error {
	out.ClaimState = v1alpha1.DeviceClaimState(in.ClaimState)
	out.State = v1alpha1.BlockDeviceState(in.State)
	return nil
}

// Convert_openebsio_DeviceStatus_To_v1alpha1_DeviceStatus is an autogenerated conversion function.
func Convert_openebsio_DeviceStatus_To_v1alpha1_DeviceStatus(in *openebsio.DeviceStatus, out *v1alpha1.DeviceStatus, s conversion.Scope) error {
	return autoConvert_openebsio_DeviceStatus_To_v1alpha1_DeviceStatus(in, out, s)
}

func autoConvert_v1alpha1_FileSystemInfo_To_openebsio_FileSystemInfo(in *v1alpha1.FileSystemInfo, out *openebsio.FileSystemInfo, s conversion.Scope) error {
	out.Type = in.Type
	out.Mountpoint = in.Mountpoint
	return nil
}

// Convert_v1alpha1_FileSystemInfo_To_openebsio_FileSystemInfo is an autogenerated conversion function.
func Convert_v1alpha1_FileSystemInfo_To_openebsio_FileSystemInfo(in *v1alpha1.FileSystemInfo, out *openebsio.FileSystemInfo, s conversion.Scope) error {
	return autoConvert_v1alpha1_FileSystemInfo_To_openebsio_FileSystemInfo(in, out, s)
}

func autoConvert_openebsio_FileSystemInfo_To_v1alpha1_FileSystemInfo(in *openebsio.FileSystemInfo, out *v1alpha1.FileSystemInfo, s conversion.Scope) error {
	out.Type = in.Type
	out.Mountpoint = in.Mountpoint
	return nil
}

// Convert_openebsio_FileSystemInfo_To_v1alpha1_FileSystemInfo is an autogenerated conversion function.
func Convert_openebsio_FileSystemInfo_To_v1alpha1_FileSystemInfo(in *openebsio.FileSystemInfo, out *v1alpha1.FileSystemInfo, s conversion.Scope) error {
	return autoConvert_openebsio_FileSystemInfo_To_v1alpha1_FileSystemInfo(in, out, s)
}

func autoConvert_v1alpha1_NodeAttribute_To_openebsio_NodeAttribute(in *v1alpha1.NodeAttribute, out *openebsio.NodeAttribute, s conversion.Scope) error {
	out.NodeName = in.NodeName
	return nil
}

// Convert_v1alpha1_NodeAttribute_To_openebsio_NodeAttribute is an autogenerated conversion function.
func Convert_v1alpha1_NodeAttribute_To_openebsio_NodeAttribute(in *v1alpha1.NodeAttribute, out *openebsio.NodeAttribute, s conversion.Scope) error {
	return autoConvert_v1alpha1_NodeAttribute_To_openebsio_NodeAttribute(in, out, s)
}

func autoConvert_openebsio_NodeAttribute_To_v1alpha1_NodeAttribute(in *openebsio.NodeAttribute, out *v1alpha1.NodeAttribute, s conversion.Scope) error {
	out.NodeName = in.NodeName
	return nil
}

// Convert_openebsio_NodeAttribute_To_v1alpha1_NodeAttribute is an autogenerated conversion function.
func Convert_openebsio_NodeAttribute_To_v1alpha1_NodeAttribute(in *openebsio.NodeAttribute, out *v1alpha1.NodeAttribute, s conversion.Scope) error {
	return autoConvert_openebsio_NodeAttribute_To_v1alpha1_NodeAttribute(in, out, s)
}
