/*
Copyright 2021 The OpenEBS Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "github.com/openebs/api/v3/pkg/apis/cstor/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCStorVolumePolicies implements CStorVolumePolicyInterface
type FakeCStorVolumePolicies struct {
	Fake *FakeCstorV1
	ns   string
}

var cstorvolumepoliciesResource = v1.SchemeGroupVersion.WithResource("cstorvolumepolicies")

var cstorvolumepoliciesKind = v1.SchemeGroupVersion.WithKind("CStorVolumePolicy")

// Get takes name of the cStorVolumePolicy, and returns the corresponding cStorVolumePolicy object, and an error if there is any.
func (c *FakeCStorVolumePolicies) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.CStorVolumePolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(cstorvolumepoliciesResource, c.ns, name), &v1.CStorVolumePolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.CStorVolumePolicy), err
}

// List takes label and field selectors, and returns the list of CStorVolumePolicies that match those selectors.
func (c *FakeCStorVolumePolicies) List(ctx context.Context, opts metav1.ListOptions) (result *v1.CStorVolumePolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(cstorvolumepoliciesResource, cstorvolumepoliciesKind, c.ns, opts), &v1.CStorVolumePolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.CStorVolumePolicyList{ListMeta: obj.(*v1.CStorVolumePolicyList).ListMeta}
	for _, item := range obj.(*v1.CStorVolumePolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested cStorVolumePolicies.
func (c *FakeCStorVolumePolicies) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(cstorvolumepoliciesResource, c.ns, opts))

}

// Create takes the representation of a cStorVolumePolicy and creates it.  Returns the server's representation of the cStorVolumePolicy, and an error, if there is any.
func (c *FakeCStorVolumePolicies) Create(ctx context.Context, cStorVolumePolicy *v1.CStorVolumePolicy, opts metav1.CreateOptions) (result *v1.CStorVolumePolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(cstorvolumepoliciesResource, c.ns, cStorVolumePolicy), &v1.CStorVolumePolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.CStorVolumePolicy), err
}

// Update takes the representation of a cStorVolumePolicy and updates it. Returns the server's representation of the cStorVolumePolicy, and an error, if there is any.
func (c *FakeCStorVolumePolicies) Update(ctx context.Context, cStorVolumePolicy *v1.CStorVolumePolicy, opts metav1.UpdateOptions) (result *v1.CStorVolumePolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(cstorvolumepoliciesResource, c.ns, cStorVolumePolicy), &v1.CStorVolumePolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.CStorVolumePolicy), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCStorVolumePolicies) UpdateStatus(ctx context.Context, cStorVolumePolicy *v1.CStorVolumePolicy, opts metav1.UpdateOptions) (*v1.CStorVolumePolicy, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(cstorvolumepoliciesResource, "status", c.ns, cStorVolumePolicy), &v1.CStorVolumePolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.CStorVolumePolicy), err
}

// Delete takes name of the cStorVolumePolicy and deletes it. Returns an error if one occurs.
func (c *FakeCStorVolumePolicies) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(cstorvolumepoliciesResource, c.ns, name, opts), &v1.CStorVolumePolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCStorVolumePolicies) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(cstorvolumepoliciesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.CStorVolumePolicyList{})
	return err
}

// Patch applies the patch and returns the patched cStorVolumePolicy.
func (c *FakeCStorVolumePolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.CStorVolumePolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(cstorvolumepoliciesResource, c.ns, name, pt, data, subresources...), &v1.CStorVolumePolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.CStorVolumePolicy), err
}
