name: Go
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.19
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.1
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run go test
      run: make test

    - name: verify dependencies
      run: make deps

    - name: verify license
      run: make license-check

    - name: verify kubegen
      run: make verify_kubegen
      env:
        GOPATH: /home/runner/work/api/go
